### ISSUE TITLE
Add `synonymizer` rules

### ISSUE THREAD

**Issue by hrshdhgd** [monarch-initiative/mondo-ingest#112]
- [X] S1: when we are doing matching, we want disorder to be replaced by disease
- [ ] S2: type 1 -> Type I
- [X] S3: 1 -> type 1
- [ ] S4: include 'the' in the label, eg abnormality of the face -> abnormality of face
- [ ] S5: of
- [ ] S6: plural
- [x] S7: 's, eg Usher's syndrome -> Usher syndrome

**Comment by matentzn** [comment]
- We should use a generic toolkit for dealing with roman numerals
- For S4, S5 we should use generic stop word removal filter
- S6 should be dealt with by a 'plural' filter

**Comment by matentzn** [comment]
@hrshdhgd 

- [ ] Make issue for oak requesting the following lexmatch preprocessors
- roman numerals
- stop word removal
- plural
