### ISSUE TITLE
ORDO ingest- issue with obsolete parents/superclass

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo-ingest#119]
For the ORDO slurp, it only allows ingestion if there is a valid parent or no parent. The parents are wrong in all cases of the ORDO ingest, the parents are obsolete in Mondo.

**Comment by joeflack4** [comment]
Ah, we forgot to check for obsoletion/deprecation. This sounds like a high priority.

**Comment by joeflack4** [comment]
@nicolevasilevsky Looks fixed I think~. If you can examine the new outputs in #124
