### ISSUE TITLE
ORDO slurp - some terms were already in Mondo

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo-ingest#120]
Another bug witht the ORDO ingest- there were a few cases where the terms were terms that were already in Mondo, see [here](https://docs.google.com/spreadsheets/d/1auHbUy_w_lHT8IcBCLsABDLQD-NFfMGI48Rb0rKddcs/edit#gid=1534835861)

Orphanet:99000 was already in the MONDO SSSOM file, so there is something buggy here :bug:

**Comment by joeflack4** [comment]
Hmm, I wonder if they were in `mondo.sssom.tsv` at the time or not. Suss. I'll look into it!

**Comment by joeflack4** [comment]
@nicolevasilevsky, @sabrinatoro (FYI), @matentzn I investigated, and this does not appear to be a problem with the slurp scripting, but is either/both of:

(a) a normal consequence of the terms having not been in Mondo at the time the ORDO slurp was last run, or
(b) these terms were in Mondo at the time ORDO slurp was run, but the `mondo.sssom.tsv` was not up-to-date.

It is possible that (a) might have been true, but I do indeed think that (b) is true.

I just updated `mondo.sssom.tsv` and re-ran, and I checked for the 3 Orphanet terms in [Nicole's spreadsheet](https://docs.google.com/spreadsheets/d/1auHbUy_w_lHT8IcBCLsABDLQD-NFfMGI48Rb0rKddcs/edit#gid=1534835861):
- Orphanet:99000: no longer in `slurp/ordo.tsv`. in `mondo.sssom.tsv`
- Orphanet:95494: no longer in `slurp/ordo.tsv`. in `mondo.sssom.tsv`
- Orphanet:435930: still in `slurp/ordo.tsv`. not in `mondo.sssom.tsv`

I looked at how our pipeline updates `mondo.sssom.tsv`:
```make
tmp/mondo.sssom.tsv:
	wget http://purl.obolibrary.org/obo/mondo/mappings/mondo.sssom.tsv -O $@
```

We do need to work eventually on auto-updating downstream artefacts when one of them changes. I know that Nico tried a GitHub action for that, but it runs out of memory / has an issue with ODK. We could run an independent server that does this stuff for us. A heavy lift either way.

Concerning `mondo.sssom.tsv` specifically, I don't know how this gets updated, but maybe there is a way to speed up how fast it updates / have it update automatically when Mondo is updated?

**Comment by joeflack4** [comment]
We can probably close this issue, but might need to open up a new one about getting `mondo.sssom.tsv` updated faster, unless that's a quick fix one of us can do.

**Comment by matentzn** [comment]
Excellent @joeflack4 consider this off your list

## Remaining action items

- [ ] @nicolevasilevsky to document why/why not and if `xref: Orphanet:435930 {source="MONDO:equivalentObsolete"}` should be in our official mappings or not. I forgot the outcome of that discussion.

**Comment by nicolevasilevsky** [comment]
Orphanet:435930 is not obsolete.

It is an MONDO:equivalentTo xref on MONDO:0008927 'colobomatous optic disc-macular atrophy-chorioretinopathy syndrome' and this seems correct.

**Comment by matentzn** [comment]
Ok this is simply then a mapping sync issue
