### ISSUE TITLE
`lexmatch` next steps: separate exact matches

### ISSUE THREAD

**Issue by hrshdhgd** [monarch-initiative/mondo-ingest#129]
- `lexmatch/unmapped_icd_lex.tsv` can have another file separated out that has exact matches (`label_1.lowercase()==label2_lowercase()`)
 - Double check[ these files](https://github.com/monarch-initiative/mondo-ingest/tree/main/src/ontology/lexmatch/mondo-only): Empty?

**Comment by hrshdhgd** [comment]
@matentzn , I figured out why [`unmapped_doid_mondo.tsv`](https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/lexmatch/mondo-only/unmapped_doid_mondo.tsv) and others are empty. When we pass the dataframe through `filter_redundant_rows()` [here](https://github.com/monarch-initiative/mondo-ingest/blob/main/src/scripts/lexmatch-sssom-compare.py#L316), the data is filtered out.

As we have designed `SSSOM`, the function [`filter_redundant_rows()`](https://github.com/mapping-commons/sssom-py/blob/master/sssom/util.py#L267), we `.group()` by either:
 - `subject_id`, `object_id` OR
 - `subject_id`,`predicate_id`, `object_id`

In the process, `comment` column which is the differentiating factor between `UNIQUE_1`, `UNIQUE_2` & `COMMON_TO_BOTH` fades away.

One solution could be considering `comment` as a column to `groupBy` as well. Thoughts?

**Comment by matentzn** [comment]
Hmm, better not add comment. I would suggest this:

1. Do _not_ use filter_redundant_rows
2. Instead, copy paste the method into your custom python pipeline and adjust it to do what you want (i.e. take comment into account).

**Comment by hrshdhgd** [comment]
Figured it out. I misspoke ... `groupBy()` has nothing to do with it however there still is a bug in `sssom-py` I need to fix.
