### ISSUE TITLE
`make mirror/X.db` creates `X.db.tmp` but not `X.db`

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/mondo-ingest#136]
## Overview
I'm trying to get `mondo-ingest` to handle creation of `semsql` databases, but I get an error towards the end of the conversion.

CC: @matentzn as FYI and if any ideas, @cmungall hoping you know what the issue might be.

### Short err
`thread 'main' panicked at 'called ``Result::unwrap()`` on an ``Err`` value: RdfXmlError { kind: Xml(EscapeError(UnrecognizedSymbol(1..4, Ok("xsd")))) }', src/[main.rs](http://main.rs/):102:8`

### Long err
Below is the relevant part of the overall stacktrace, with `RUST_BACKTRACE=1`. Here is the full stacktrace of the make goal with `RUST_BACKTRACE=full`: [stacktrace.txt](https://github.com/monarch-initiative/mondo-ingest/files/10473566/stacktrace.txt)

```
cp .template.db mirror/ordo.db.tmp && \
rdftab mirror/ordo.db.tmp < mirror/ordo.owl && \
sqlite3 mirror/ordo.db.tmp -cmd '.separator "\t"' ".import mirror/ordo-relation-graph.tsv entailed_edge" && \
gzip -f mirror/ordo-relation-graph.tsv && \
cat /usr/local/lib/python3.10/dist-packages/semsql/builder//indexes/*.sql | sqlite3 mirror/ordo.db.tmp && \
mv mirror/ordo.db.tmp mirror/ordo.db
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RdfXmlError { kind: Xml(EscapeError(UnrecognizedSymbol(1..4, Ok("xsd")))) }', src/[main.rs](http://main.rs/):102:8

stack backtrace:
   0: rust_begin_unwind
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/result.rs:1785:5
   3: rdftab::main
```

## Reproducibility
ORDO chosen here arbitrarily. If you want something easier to replicate, I can upload `ordo.owl` to google drive and link it.
1. Have docker running and an updated version of `obolibrary/odkfull` `dev`.
2. From updated `main` on a clone of `mondo-ingest`, from `src/ontology/`, run: `sh run.sh make mirror/ordo.db`

## Discussion
Related: https://github.com/INCATools/semantic-sql/issues/67

Looks like this error is occurring in `rdftab`, but I'm not sure why.

This problem happens for the following ontologies:
- omim
- ordo

Doesn't happen for these:
- ncit
- do / doid

## Possible solutions
Fix RDF/XML invalidities. See: 
- #139

**Comment by joeflack4** [comment]
Sounds good, I'll give that a go. I'll make a note to get the skinny on what I still don't understand about mirror/imports vs components at a future 1:1.

**Comment by joeflack4** [comment]
@matentzn I'm re-opening this because I can't think of the best way to approach this problem right now. Here's where I would like your advice:

We want to use OAK, which really means we want to use `semsql`, as it's more stable, faster, and full featured than the other OAK implementations. However, we can't use it on the `mirror/` files because there are some issues which we discussed above.

However, I tried using the `components/` files, but they seemed less complete for my purposes. When I was trying to query  for labels, I was getting a lot of missing labels for ORDO (much higher than n=542). When I queried the `mirror/ordo.owl`, I got a much lower amount of missing labels (n=542).

Related: ORDO missing labels ([see comment in PR](https://github.com/monarch-initiative/mondo-ingest/pull/111#discussion_r1086121250))

**Comment by matentzn** [comment]
Can we discuss this is a 10 min call at 10am EST?

**Comment by joeflack4** [comment]
Sorry I did not see this message. I will add this to my agenda to discuss at our next one-on-one, or near the end of the group technical call if there's time.

**Comment by joeflack4** [comment]
We discussed and indeed will continue to query `mirror/` for terms/labels using SPARQL. Can use `components/` using semsql/oak for other use cases.
