### ISSUE TITLE
`No rule to make target 'mirror/ONTOLOGY.owl'`

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/mondo-ingest#137]
## Overview
For the progress report, I'm trying to get `semsql` `.db`s to extract labels. `src/ontology/mirror/` is not fully populated with `.owl`s for each ontology, so I'm trying to do that, but failing.

@matentzn Can you offer some advice? Do you think my proposed "possible cause" is the issue? If so, any idea how to solve?

## Error
```
(mondo-ingest) mmake mirror/ordo.owl
Running  with -Xmx20G of memory for ROBOT and Java-based pipeline steps.
mondo-ingest.Makefile:34: warning: overriding recipe for target 'components/omim.owl'
Makefile:365: warning: ignoring old recipe for target 'components/omim.owl'
mondo-ingest.Makefile:49: warning: overriding recipe for target 'components/ordo.owl'
Makefile:376: warning: ignoring old recipe for target 'components/ordo.owl'
mondo-ingest.Makefile:68: warning: overriding recipe for target 'components/ncit.owl'
Makefile:387: warning: ignoring old recipe for target 'components/ncit.owl'
mondo-ingest.Makefile:77: warning: overriding recipe for target 'components/doid.owl'
Makefile:398: warning: ignoring old recipe for target 'components/doid.owl'
mondo-ingest.Makefile:98: warning: overriding recipe for target 'component-download-icd10cm.owl'
Makefile:405: warning: ignoring old recipe for target 'component-download-icd10cm.owl'
mondo-ingest.Makefile:103: warning: overriding recipe for target 'components/icd10cm.owl'
Makefile:409: warning: ignoring old recipe for target 'components/icd10cm.owl'
mondo-ingest.Makefile:118: warning: overriding recipe for target 'components/icd10who.owl'
Makefile:420: warning: ignoring old recipe for target 'components/icd10who.owl'
mondo-ingest.Makefile:133: warning: overriding recipe for target 'mondo-ingest-full.owl'
Makefile:546: warning: ignoring old recipe for target 'mondo-ingest-full.owl'
mondo-ingest.Makefile:416: warning: overriding recipe for target 'help'
Makefile:617: warning: ignoring old recipe for target 'help'
make: *** No rule to make target 'mirror/ordo.owl'.  Stop.
```

 ## Reproducibility
ORDO chosen arbitrarily.
1. Have docker running and an updated version of `obolibrary/odkfull` `dev`.
2. Make sure there is no existing `mirror/ordo.owl`.
3. From updated main on a clone of `mondo-ingest`, from `src/ontology/`, run: `sh run.sh make mirror/ordo.owl`

## Possible causes
1. Does this have something to do with the warnings `Makefile:LINE_NUM: warning: ignoring old recipe for target 'GOAL_NAME'`? I think the `component-download-ONTO_NAME.owl` goals might be a dependency.

## Additional information
Just glancing at some existing, relevant goals:

```make
$(MIRRORDIR)/%.owl: mirror-% | $(MIRRORDIR)
	if [ $(IMP) = true ] && [ $(MIR) = true ] && [ -f $(TMPDIR)/mirror-$*.owl ]; then if cmp -s $(TMPDIR)/mirror-$*.owl $@ ; then echo "Mirror identical, ignoring."; else echo "Mirrors different, updating." &&\
		cp $(TMPDIR)/mirror-$*.owl $@; fi; fi
```

```make
.PHONY: component-download-ordo.owl
component-download-ordo.owl: | $(TMPDIR)
	if [ $(MIR) = true ] && [ $(COMP) = true ]; then $(ROBOT) merge -I http://www.orphadata.org/data/ORDO/ordo_orphanet.owl \
	annotate --ontology-iri $(ONTBASE)/$@ $(ANNOTATE_ONTOLOGY_VERSION) -o $(TMPDIR)/$@.owl; fi
```

**Comment by matentzn** [comment]
Now I also understand the other problem you described with the RDF/XML issue.

Mirrors for components have to be downloaded using:

```
sh run.sh make component-download-ordo.owl
```

The mirror one is only for mirrors of `imports`.. This is a bit confusing, sorry.

**Comment by matentzn** [comment]
Basically your report code should probably depend on `component-download-ordo.owl` even if this is a PHONY goal technically speaking

**Comment by joeflack4** [comment]
Ok, I see I see. I can learn more about mirror/import some other time. For now, I can depend on: `component-download-ONTOOGY.owl`

How about depending on `components/ONTOLOGY.owl` though?

Example for ORDO:
```make
$(COMPONENTSDIR)/ordo.owl: $(TMPDIR)/ordo_relevant_signature.txt config/properties.txt
	if [ $(COMP) = true ]; then $(ROBOT) remove -i $(TMPDIR)/component-download-ordo.owl.owl --select imports \
		merge \
		rename --mappings config/property-map-1.sssom.tsv --allow-missing-entities true \
		rename --mappings config/property-map-2.sssom.tsv --allow-missing-entities true \
		query \
			--update ../sparql/fix_partof.ru \
			--update ../sparql/fix_deprecated.ru \
			--update ../sparql/fix_complex_reification.ru \
			--update ../sparql/fix_xref_prefixes.ru \
			--update ../sparql/fix-labels-with-brackets.ru \
			--update ../sparql/ordo-construct-subclass-from-part-of.ru \
			--update ../sparql/ordo-construct-subsets.ru \
			--update ../sparql/ordo-construct-d2g.ru \
			--update ../sparql/ordo-replace-annotation-based-mappings.ru \
		filter -T $(TMPDIR)/ordo_relevant_signature.txt --trim false \
		remove -T config/properties.txt --select complement --select properties --trim true \
		annotate --ontology-iri $(URIBASE)/mondo/sources/ordo.owl --version-iri $(URIBASE)/mondo/sources/$(TODAY)/ordo.owl -o $@; fi
```

**Comment by matentzn** [comment]
> How about depending on components/ONTOLOGY.owl though? Those are not PHONY, but I don't know if there is some reason why I would not want to depend on those.

Totally fine to depend on these! In fact, you should only ever depend on NON PHONY goals. So the other way around is the real issue.

> A lot of my goals use a reports/mirror_signature-ONTOLOGY.tsv as an input, including the current progress monitor I'm making. Should I consider changing this to reports/component_signature-ONTOLOGY.tsv (for my current progress report and potentially other cases?

No, its still a `mirror`, i.e. the raw ontology being downloaded. I think you should leave it like it is!

**Comment by joeflack4** [comment]
I still have some confusion about this, but it's in my notes / agenda to discuss w/ Nico whenever we have more time.

As for the immediate engineering need where this came up, that has been solved by Nico's suggestions, so I'm closing this.
