### ISSUE TITLE
Add ICD11 mappings back

### ISSUE THREAD

**Issue by hrshdhgd** [monarch-initiative/mondo-ingest#140]
Follow-up to : https://github.com/monarch-initiative/mondo-ingest/pull/135.

As per this PR we are `DELETE`ing the prefix `ICD11:` as a `dbxref`. We need to add it back when needed.

**Comment by joeflack4** [comment]
Hey @hrshdhgd , do you think there is still some work needed? This isn't related to #16 is it? Is this just about adding an ICD11 `dbxref` to a SPARQL query?

**Comment by matentzn** [comment]
This is related to 

https://github.com/monarch-initiative/mondo-ingest/blob/main/src/sparql/rm_xref_by_prefix.ru#L19

where we exclude ICD11 mappings from DOID (and other sources), once we have an active alignment process with ICD11, we should add this back.

**Comment by joeflack4** [comment]
@hrshdhgd Just FYI, #434 will be merged soon. I suppose whenever you have time, you can handle this, maybe after the merge?

**New ICD11Foundation prefixes**
Or maybe you can tackle it whenever, as it looks to me like all of the new ICD11Foundation prefixes are already in all of the right places in `develop`. `icd11.foundation` has been added, along with 2 others. `icd11.foundation` is the one you need to be primarily concerned with, as it is on all the classes. There's also `icd11.z`, but IIRC this is just for retired classes, and there aren't many. The 3rd one is `icd11.schema`.

**Old ICD11 prefix**
I don't know if we plan on removing `ICD11`, but in my opinion @hrshdhgd @twhetzel @hrshdhgd, we may want to rename it. For example, all of the instances of `ICD-11` in Orphanet are references to ICD11MMS (Morbidity and Mortality Statistics), so I suggest we rename `ICD11` to `ICD11MMS` if Orphanet comprises 100% of such references, or if the other references also refer to ICD11MMS.

**Comment by hrshdhgd** [comment]
#486 takes care of this @joeflack4

**Comment by joeflack4** [comment]
@hrshdhgd Thanks ill take a look!
