### ISSUE TITLE
Add instructions for syncing ontologies (the old way)

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#17]
So far, @cmungall has been running the alignment for ontologies other than ORDO and OMIM (which @nicolevasilevsky and I were syncing ourselves). 

@cmungall could you provide us with a step by step instructions on how we can align while the new pipeline is still underway? This will help us to:

- sync up while we still cant finish the new people (grrrr)
- have a reference to review to ensure the new pipeline is designed correctly

This is how we sync up with OMIM and ORDO:

https://github.com/monarch-initiative/mondo/blob/master/src/ontology/Makefile#L1153

Can we use exactly the same make target for other ontologies like DO and NCIT? What preprocessing is needed to run the alignment?

**Comment by nlharris** [comment]
Is this still needed?

**Comment by matentzn** [comment]
No, we will go all in on the new one.
