### ISSUE TITLE
NCIT: `mirror_signature`: `OutOfMemoryError: Java heap space`

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/mondo-ingest#171]
## Overview
@matentzn The old NCIT memory issue rears its ugly head again, like some kind of loch ness monster.

This happens when I run `sh run.sh ...` to try to get the `mirror_signature` (with or without `-incl-deprecated`), which runs:
`robot --catalog catalog-v001.xml query -i tmp/component-download-ncit.owl.owl --query ../sparql/classes-incl-deprecated.sparql reports/mirror_signature-incl-deprecated-ncit.tsv`

For now, I'm using a cached version of the `mirror_signature-ncit.tsv` for [the progress report](https://github.com/monarch-initiative/mondo-ingest/pull/111).

## Error
`error: Exception in thread "main" java.lang.OutOfMemoryError: Java heap space`
[log.txt](https://github.com/monarch-initiative/mondo-ingest/files/10614135/log.txt)

### 1. Increase Docker memory even more than 20GB?
I can try this, but it doesn't seem sustainable.
<img width="863" alt="ncit out of mem" src="https://user-images.githubusercontent.com/13045020/216852883-eb51646e-b6fd-4a95-913d-bab97cb35171.png">

### 2. Increase memory efficiency?
I don't know where I'd begin to get started here. But I will say this; it seems strange that a simple query to get term IDs alone requires 20GB. Perhaps `robot` is doing a lot of initialization; stuff that perhaps it doesn't need to do for such a simple use case. I think the same is possibly true for `rdflib` and `oaklib` in cases like these.

**Comment by matentzn** [comment]
What is the local Java memory you are using inside docker? (`cat run.sh.conf`)

20GB is way over the top. OAK would be better for this and we can switch if you like

**Comment by joeflack4** [comment]
@matentzn 
`run.sh.conf`:
```sh
ODK_TAG=dev
ODK_DEBUG=yes
```

In `run.sh`:
```sh
ODK_JAVA_OPTS=${ODK_JAVA_OPTS:--Xmx20G}
```

Looks like 20GB .

Though it won't effectively change anything, should I add `ODK_JAVA_OPTS=--Xmx20G` to the `run.sh.conf`?

I think you're right; I should use OAK for NCIT specifically right now (eventually for all of them).

**Comment by matentzn** [comment]
No need to add that env to run.sh.conf; you can, if you want, but no need. Maybe we have to go to OAK now..

**Comment by joeflack4** [comment]
I got most of the way through the OAK refactor yesterday for NCIT. It looks like I'm not having any more OAK / semsql issues with this workflow, so I'll likely refactor the whole script to use OAK (assuming I have no issues converting any of the `components/` ontologies to semsql).

**Comment by joeflack4** [comment]
fixed w/ OAK
