### ISSUE TITLE
Add a GitHub action to Mondo that automatically creates PRs adding new mappings

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#175]
This PR should run once per week, and do the following things:

1. Add a make goal to src/ontology/mondo.Makefile, called 

```
$(TMPDIR)/new-exact-matches-%.tsv:
	wget....

$(TMPDIR)/new-exact-matches-%.owl: $(TMPDIR)/new-exact-matches-%.tsv
	$(ROBOT) template --template $< -o $@

update-%-mappings: $(TMPDIR)/new-exact-matches-%.owl
	$(ROBOT) merge -i $(SRC) -i $< -o tmp/mondo-edit.obo && mv tmp/mondo-edit.obo $(SRC)
```

2. Add a Github action that runs this goal (workflow dispatch and once per week, for all ontologies we care about) and make a PR.

**Comment by hrshdhgd** [comment]
Can I add this workflow directly to the main branch so I can iteratively test it?

**Comment by matentzn** [comment]
Yes!

**Comment by hrshdhgd** [comment]
First draft at: https://github.com/monarch-initiative/mondo/blob/master/.github/workflows/mappings.yml
