### ISSUE TITLE
Remove all "inactive" classes from ORDO from ORDO ingest?

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#183]
Should all of these https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_C041&lang=en&viewMode=All&siblings=false

be excluded from ORDO, i.e. added to the exclusion table?

**Comment by sabrinatoro** [comment]
Thinking about what purpose would ingest these inactive classes would be. 
![Screenshot 2023-02-13 at 9 27 23 AM](https://user-images.githubusercontent.com/12737987/218529304-a976e460-21bf-4f11-9f7a-6550edb8bf3e.png)

- the deprecate and obsolete classes would not be available in orphanet anymore. Therefore, I think it is safe to add these to the list of excluded terms. 
Note: the ID that are already in Mondo would have to be updated to "Mondo:EquivalentObsolete"

- the "non rare" branch is trickier: we want all the diseases in Mondo (rare and non-rare)
BUT, the orphanet ids (and any other information about the terms) are not available on the orphanet website, therefore I don't think it is useful to have an x-ref to an orphanet ID that is not available in orphanet anymore. 
Note: same comment about having to update the one existing in Mondo to "Mondo: EquivalentObsolete".

Therefore I think we can safely exclude all the classes under "inactive" in ordo.

@nicolevasilevsky, do you want to weight in before I add these to the exclusion list?

**Comment by matentzn** [comment]
Remeber you only need to add the parent to the exclusion list, and say that children should be excluded too.

**Comment by matentzn** [comment]
Also, you need to advice @joeflack4 on whether all of these terms should be tagged, by the ingest pipeline as owl:deprecated. The question you need to answer is:

Are from their intention, these "inactive" classes to be considered deprecated?

**Comment by nicolevasilevsky** [comment]
I spot-checked a couple of the non-rare disorders in Orphanet and they are already xref'd in Mondo. It seems like we should maintain these xrefs.

Orphanet does have obsoleted classes, so I don't think these are considered obsolete in Orphanet. I don't really know what they mean by inactive, maybe they aren't maintained or kept up to date? Should we have a tag in Mondo that notes these are inactive in Orphanet?

**Comment by matentzn** [comment]
> Orphanet does have obsoleted classes

Can you tell me how I can tell from https://www.orphadata.com/ordo/ which classes are obsolete?

**Comment by sabrinatoro** [comment]
>Orphanet does have obsoleted classes, so I don't think these are considered obsolete in Orphanet.

@nicolevasilevsky I am assuming you meant "does not have" obsoleted classes. 
That being said, if you search their website, you cannot find any of these classes, and they are in the "inactive" branch, which seems very much like an obsoletion (though they don't call it that way). 
"inactive" branch = A clinical entity that has been excluded from the Orphanet nomenclature. This includes obsolete entities, deprecated entities, and entities that have been inactivated because they are not rare in Europe.
Therefore, even if we have them in Mondo, it looks like they refer to something that has been excluded from Orphanet.

**Comment by nicolevasilevsky** [comment]
Ah, thanks for clarifying, Sabrina! I'm fine with excluding these in Mondo too.

**Comment by sabrinatoro** [comment]
Thank you @nicolevasilevsky . 
I will update the exclusion list to exclude this whole branch.
