### ISSUE TITLE
Links to MedGen

### ISSUE THREAD

**Issue by PabloBotas** [monarch-initiative/mondo-ingest#193]
Hi,
According to [https://mondo.monarchinitiative.org/pages/sources/](https://mondo.monarchinitiative.org/pages/sources/), MedGen terms should be linked from Mondo terms, yet I don't see a lot of terms are linked to it in the obo file. I do see links to Mondo in MedGen, but not viceversa. Is this intended? Do you know of a resource establishing this mapping?

Thanks!

**Comment by matentzn** [comment]
Thank you @PabloBotas for the push, we have had the medgen sync on our agenda for a long long time, and we should probably just prioritise it now.

@joeflack4 Lets talk about this at our next call - I would like to at least fold in the mappings provided by Medgen asap.

**Comment by kanems** [comment]
MedGen has a report on our FTP Site (https://ftp.ncbi.nlm.nih.gov/pub/medgen/) of all the ID Mappings including MedGen's mapping of Mondo IDs to a CUI, or if no suitable CUI is available from UMLS (C#) Our own supplemental "CUI-like" code (CN#).
This is freely available should be machine readable. [MedGenIDMappings.txt.gz](https://ftp.ncbi.nlm.nih.gov/pub/medgen/MedGenIDMappings.txt.gz)

**Comment by nicolevasilevsky** [comment]
Thanks all! I'll move this ticket to the Mondo ingest tracker.

**Comment by PabloBotas** [comment]
Thank you all for picking this up so quickly!!

**Comment by joeflack4** [comment]
@matentzn @twhetzel What are the remaining sub-tasks that would render this completed?

I'm currently seeing MedGen refs in `mondo-edit.obo`, but not `mondo.sssom.tsv`.

**Comment by matentzn** [comment]
MedGen xrefs are not mappings in the strict sense - they dont have to be in the sssom. As soon as your latest batch (updated xrefs) is updated in mondo-edit.obo we can can close this issue.

**Comment by joeflack4** [comment]
Not 100% sure, but I think `mondo-edit.obo` got updated a few months ago, and this can be closed now.

**Comment by matentzn** [comment]
Yes, all MEDGEN mappings are now in Mondo! Thanks!
