### ISSUE TITLE
non-OBO terms with OBO PURLs

### ISSUE THREAD

**Issue by balhoff** [monarch-initiative/mondo-ingest#199]
MONDO contains terms using unregistered OBO namespaces, e.g.:

- http://purl.obolibrary.org/obo/OMIM_424500
- http://purl.obolibrary.org/obo/SCTID_716594002
- http://purl.obolibrary.org/obo/ONCOTREE_GINET
- http://purl.obolibrary.org/obo/OMIMPS_

There may be others.

**Comment by matentzn** [comment]
I fixed it now in Mondo, will show up in the next release.
