### ISSUE TITLE
Questions about unmapped_doid_lex_exact.tsv

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo-ingest#200]
@hrshdhgd and @matentzn 
Could you tell me how to proceed about the following found in https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/lexmatch/unmapped_doid_lex_exact.tsv

1) some MONDO id is on more than one line, but match to the same DOid. 
For example, lines 13-14: 

subject_id | predicate_id | object_id | object_label | subject_label | mapping_justification | mapping_tool | confidence | subject_match_field | object_match_field | match_string | comment
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
MONDO:0007110 | MONDO:equivalentTo | DOID:0111895 | Diamond-Blackfan anemia 1 | Diamond-Blackfan anemia 1 | semapv:LexicalMatching | oaklib | 0.9411764706 | oio:hasDbXref | oio:hasDbXref | omim:105650 | LEXMATCH
MONDO:0007110 | MONDO:equivalentTo | DOID:0111895 | Diamond-Blackfan anemia 1 | Diamond-Blackfan anemia 1 | semapv:LexicalMatching | oaklib | 0.9411764706 | oio:hasDbXref | oio:hasDbXref | mesh:c567302 | LEXMATCH

**Should I remove the duplicate lines when merging into Mondo?** 
I am assuming based on the .tsv that we only record the mapping and not how the mapping was done (??), ie the fact that there is a mapping based on hasDbXref. Therefore I think it is ok to remove the duplicate MondoID-DOid

2) What does ">A sssom:object_label" means in the ROBOT template?

subject_id | predicate_id | object_id | object_label
-- | -- | -- | --
ID | A oboInOwl:hasDbXref | >A oboInOwl:source | >A sssom:object_label

Some mapping are made based on matching of "hasDbXref", so the "object_label" is confusing to me. Is there any documentation on what these sources "sssom:~" refer to? 

Thank you!

**Comment by matentzn** [comment]
> Therefore I think it is ok to remove the duplicate MondoID-DOid

Yes, feel free to remove these. Duplicate rows correspond to different mapping rules resulting in the mapping. Even if you don't remove them, nothing bad will happen.

> What does ">A sssom:object_label" means in the ROBOT template?

This has _nothing_ to do with the mapping rule, this is just an additional piece of metadata I found useful: the label of the object ID.  This helps eyeballing if the mapping makes sense. The `subject_match_field` etc documents which fields the matcher used for mapping, and this may or may not have been the label.

**Comment by sabrinatoro** [comment]
> This has nothing to do with the mapping rule, this is just an additional piece of metadata I found useful: the label of the object ID. 

I got confused and thought the match was on the x-ref and not on the label... BUT I was incorrect as the labels between object and subject are the same.  So it makes sense.

Thank you Nico!

**Comment by sabrinatoro** [comment]
Closing this issue as there is no action item and all questions have been answered.
