### ISSUE TITLE
Bugfix: GitHub action for docs

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/mondo-ingest#202]
## Overview
The [action for building the docs](https://github.com/monarch-initiative/mondo-ingest/actions/workflows/docs.yml) has been broken for a while.

## Error details
Annoyingly, it looks like it's breaking on building `numpy` ([example](https://github.com/monarch-initiative/mondo-ingest/actions/runs/4195761805/jobs/7275765107)).

Short err: `ERROR: Failed building wheel for numpy`
Full err: [log](https://github.com/monarch-initiative/mondo-ingest/actions/runs/4195761805/jobs/7275765107)

**Comment by matentzn** [comment]
The problem can be solved by renaming requirements.txt in the top level of the repo.

https://github.com/monarch-initiative/mondo-ingest/blob/main/requirements.txt

Sorry about that, this is a known issue:

https://github.com/INCATools/ontology-development-kit/issues/506

**Comment by joeflack4** [comment]
ah i see i see

**Comment by joeflack4** [comment]
So far, fixed the original [python requirements issue](https://github.com/monarch-initiative/mondo-ingest/actions/runs/4331200503/jobs/7562889212). Addressed a [config file misspelling](https://github.com/monarch-initiative/mondo-ingest/actions/runs/4332510546/jobs/7565051210). [Works now](https://github.com/monarch-initiative/mondo-ingest/actions/runs/4332556282/jobs/7565124931)! 
https://monarch-initiative.github.io/mondo-ingest/
