### ISSUE TITLE
incorrect ROBOT template created in the mapping files

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo-ingest#205]
For example: https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/lexmatch/unmapped_doid_lex_exact.tsv 
Currently is: 
subject_id | predicate_id | object_id | object_label
-- | -- | -- | --
ID | A oboInOwl:hasDbXref | >A oboInOwl:source | >A sssom:object_label
MONDO:0000087 | MONDO:equivalentTo | DOID:0080918 | polymicrogyria
MONDO:0000136 | MONDO:equivalentTo | DOID:0080753 | keratosis follicularis spinulosa decalvans

should be

subject_id | **object_id** | **predicate_id** | object_label
-- | -- | -- | --
ID | **A oboInOwl:hasDbXref** | **>A oboInOwl:source** | >A sssom:object_label
MONDO:0000087 | DOID:0080918 | MONDO:equivalentTo | polymicrogyria
MONDO:0000136 | DOID:0080753 | MONDO:equivalentTo | keratosis follicularis spinulosa decalvans

That is: 
- **object_id** column should have **A oboInOwl:hasDbXref** on row2
- **predicate_id** column should have **>A oboInOwl:source** on row2

**Comment by hrshdhgd** [comment]
This should be fixed in the next PR I'm currently working on.
