### ISSUE TITLE
mapping issue: lexicalMatching  label vs "partial" synonym

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo-ingest#207]
https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/lexmatch/unmapped_doid_lex.tsv

DOID:0081093 - acute myeloid leukemia with t(8;21); (q22; q22.1)
was mapped to multiple Mondo id (3 examples): 
MONDO:0100376 - acute myeloid leukemia, t(9;11)(p21.3;q23.3)
MONDO:0100377 - acute myeloid leukemia, t(10;11)(p12;q23)
MONDO:0100380 - acute myeloid leukemia, t(4;11)(q21;q23)

based on: 

subject_match_field | object_match_field | match_string
-- | -- | --
rdfs:label | oio:hasExactSynonym | acute myeloid leukemia, t

It looks like the matching was based on partial name of the synonym, which lead to incorrect mapping.

**Comment by sabrinatoro** [comment]
This example might shine some light on what  is going on: 

MONDO:0035942 | B-lymphoblastic leukemia/lymphoma with t(12;21)(p13.2;q22.1) | MONDO:equivalentTo | DOID:0080645 | B-lymphoblastic leukemia/lymphoma with ETV6-RUNX1 | semapv:LexicalMatching | oaklib | 0.8 | oio:hasExactSynonym | oio:hasExactSynonym | b-lymphoblastic leukemia/lymphoma with t; etv6-runx1 | LEXMATCH
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --


it looks like what was in the parenthesis, ie (12;21)(p13.2;q22.1), was removed.

**Comment by matentzn** [comment]
@hrshdhgd I think we should remove the () rule from the mapping rules, and preprocess the ingests instead by stripping out brackets known to be redundant, i.e. ICD10CM.
