### ISSUE TITLE
Slurp IDs persistence

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/mondo-ingest#216]
## Overview
I was looking at big slurp diffs and the cause is lack of persistence. I remember bringing this up briefly at some point, that these candidate IDs aren't preserved anywhere and successive slurp runs don't know anything about them. Instead, the same ID range is being used each time:

```make
slurp/%.tsv: ...
	python3 $(SCRIPTSDIR)/migrate.py --min-id 850000 --max-id 999999 ...
```

## Example
Observe, for example, how candidate ID `MONDO:0850032` appears different over time / in different artefacts.

I combined 3 rows from 3 different tables. Row 1 is from `slurp/doid.tsv` from the previous slurp run. Row 2 is from `slurp/doid.tsv` this slurp run. Row 3 is from `slurp/icd10cm.tsv` this slurp run.

|mondo_id     |mondo_label              |xref         |xref_source       |original_label           |definition   |parents      |
|-------------|-------------------------|-------------|------------------|-------------------------|-------------|-------------|
|ID           |LABEL                    |A oboInOwl:hasDbXref|>A oboInOwl:source SPLIT=&#124;|                         |A IAO:0000115|SC %         |
|MONDO:0850032|gastroesophageal cancer  |DOID:0080374 |MONDO:equivalentTo|gastroesophageal cancer  |             |MONDO:0002516|
|MONDO:0850032|nephrotic syndrome type 5|DOID:0080380 |MONDO:equivalentTo|nephrotic syndrome type 5|             |             |
|MONDO:0850032|other forms of tularemia |ICD10CM:A21.8|MONDO:equivalentTo|Other forms of tularemia |             |MONDO:0018077|

### 1. Same IDs being used between different `slurp/%.tsv` within the same run.
**Possible solution**: The path to the `slurp/` dir should be used as an input. When slurping, we would glob on all `slurp/*.tsv` files, get the `mondo_id`s for all those files, and store the in a set, not to be re-used. We could then convert these to integers and take the `max()`, and use that as the effective next candidate ID. I suppose if we do this, we would no longer need the `--min-id` arg in the makefile (which is set to `850000`). That arg would have only been necessary for the first run.

### 2. Assigned IDs from a previous run are being ignored
Maybe this is not a huge problem? One of the inputs for the slurp is `mondo.sssom.tsv`. If some of these slurp candidates are integrated into Mondo, they _should_ appear in the `mondo.sssom.tsv` in the next run and should not be re-used. However, I could still see this causing some problems/confusion. 

**Possible solution**: If this is a problem, we need a way to preserve previous slurp runs, and use them as an input in the next slurp. There are many ways to save/reuse this data. We could have a `slurp/runs/` dir, and in that, `YYYY-MM-DD` dirs for each run. Then, when we run successive slurps, these slurp candidate mappings will be re-used. The result would be that each `YYYY-MM-DD` dir would only store _new_ slurp candidates that were not previously proposed in a previous run. Additionally, we can still have `slurp/%.tsv`s in the root of `slurp/`, above the `slurp/runs/` dir, and these files would simply be a concatenation of all of the corresponding `slurp/runs/YYYY-MM-DD/%.tsv`s for that given ontology.

---

@matentzn What do you think? Is this not as big of a problem as I am thinking or am I on to something? I am also open to alternative solutions.

**Comment by matentzn** [comment]
I like solution 1) reading the current slurp, and only adding IDs for newly found content!

**Comment by joeflack4** [comment]
@matentzn Alright, sounds good. It feels a bit weird for me to be storing nested dirs of TSVs to persist stuff like this. It's at least consistent w/ the spirit of committing artefacts to version control. A single file approach would probably be better actually, but I'll likely stick with what I originally proposed.

I think I'll go ahead and do this, and re-run the slurp to fix this ID issue before I merge: 
- #210

**Comment by matentzn** [comment]
Sounds good, thank you!
