### ISSUE TITLE
Should "MONDO:includedEntryInOMIM" be manifested at skos:closeMatch?

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#225]
Right now, the OMIM included xrefs are basically not taken into account during mapping, which may result in some valuable information being lost.

Should "MONDO:includedEntryInOMIM" be manifested at skos:closeMatch?

@sabrinatoro

**Comment by sabrinatoro** [comment]
The "MONDO:includedEntryInOMIM" can include a lot of things: other diseases or susceptibility to diseases. 
Also, these MONDO:includedEntryInOMIM represent diseases for which there is not much known and they are adding it to an existing term until they have enough information/reason to create an entry specifically for these terms. 

I think we need to treat the included terms in OMIM as if they were different omim entries. 

> Should "MONDO:includedEntryInOMIM" be manifested at skos:closeMatch?

I am not sure what you mean (ie please let me know if this is not what you are asking), but I don't think they should become a close match to mondo terms that are equivalent to the omim id shared between the omim main entry and the "included" one.

**Comment by sabrinatoro** [comment]
yes, "relatedMatch" would be the most appropriate mapping.

**Comment by matentzn** [comment]
Thank you, I made a PR to fix this issue: https://github.com/monarch-initiative/mondo/pull/6016
