### ISSUE TITLE
Mappings: mapping to a term obsoleted at the source

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo-ingest#226]
## Overview
From here: 
https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/lexmatch/unmapped_ncit_lex.tsv

subject_id | subject_label | predicate_id | object_id | object_label | mapping_justification | mapping_tool | confidence | subject_match_field | object_match_field | match_string | comment
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
MONDO:0009691 | mycosis fungoides | MONDO:equivalentTo | NCIT:C27800 | Mycosis Fungoides (Working Formulation) | semapv:LexicalMatching | oaklib | 0.8497788952 | rdfs:label | rdfs:label | mycosis fungoides | LEXMATCH

The NCIT concept is obsoleted according to https://ncithesaurus.nci.nih.gov/ncitbrowser/pages/concept_details.jsf

note: so far, this is the only example, maybe this will be resolved after we re-run the mapping

## Depends on
- #192

**Comment by sabrinatoro** [comment]
other example: 


MONDO:0019468 | T-cell prolymphocytic leukemia | MONDO:equivalentTo | NCIT:C70649 | T-Cell Chronic Lymphocytic Leukemia | semapv:LexicalMatching | oaklib | 0.8 | oio:hasExactSynonym | rdfs:label | t-cell chronic lymphocytic leukemia | LEXMATCH
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by matentzn** [comment]
Important interaction of Joes work with Harshads. I am running a new release now. @joeflack4 this ticket can be closed if Sabrina's examples show up in the exclusion list of the next run.

**Comment by joeflack4** [comment]
Did an initial rerun, and these two terms continue to not show up in the exclusions. I think this is related to #227, so will address that one and come back to this.

**Comment by matentzn** [comment]
I am not sure how we decided to deal with obsolete classes in the the progress monitor, but we do _not want to slurp nor map_ obsolete terms; we do, however, want to _sync_ them up, which is the part of the process that you developed for syncing obsoleted. This is complicated, but makes sense:

If a term is obsolete at the source, there is no point to 
   - map it with Mondo if it is not already mapped.
   - Import it into Mondo if it is not already imported.

The progress monitor should reflect this somehow, by adding _obsolete unmapped_ as a new category that is removed from the _unmapped mappable_.

**Comment by joeflack4** [comment]
Hey @matentzn duly noted; going to re-read this tomorrow just in case I missed something. However, I think you missed the key point in my investigation above. The primary issue here is that these terms are not showing up as obsolete in the pipeline because of #192. The reason they're showing up as obsolete to Sabrina is because she's looking at the NCIT browser, which is fresher than our copy of NCIT.

**Comment by matentzn** [comment]
No no, I did understand that - this all makes sense.

**Comment by matentzn** [comment]
PS: I can run the slurp pipeline from now on! (Bigger machine)

**Comment by joeflack4** [comment]
@matentzn So I re-read what you said, and it looks like what I need to know / do is:
1. [Progress monitor stats table](https://github.com/monarch-initiative/mondo-ingest/blob/main/docs/reports/unmapped.md): Add a column called `Tot obsolete unmapped` or `Tot deprecated unmapped`, directly to the right of the `Tot deprecated` column
2. Unmapped terms table ([example: DO](https://github.com/monarch-initiative/mondo-ingest/blob/main/docs/reports/unmapped_doid.md)): Add a second table (to the bottom?) called `Unmapped obsolete` or `Unmapped deprecated`, with the column `subject_id`. I could add a `subject_label` column too, but I think that there will probably not be any labels in all cases.

Does this sound correct?

**Comment by matentzn** [comment]
1. is correct, and I dont think 2 is really necessary. I think you should only do 1, and make sure that column is not counted in the `mappable` column.
