### ISSUE TITLE
Extract mappings from ORDO

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#23]
This is specifically difficult because of ORDOs strange metadata logic.

If you look at ordo (run `sh run.sh make refresh-ordo`) you can find in `src/ontology/mirror/ordo.owl` some lines like this:

The `sh` command will populate this folder.

```
  <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://www.orpha.net/ORDO/Orphanet_101206"/>
        <owl:annotatedProperty rdf:resource="http://www.geneontology.org/formats/oboInOwl#hasDbXref"/>
        <owl:annotatedTarget>ICD-10:Q22.2</owl:annotatedTarget>
        <obo:ECO_0000218 xml:lang="en">- NTBT (ORPHA code&apos;s Narrower Term maps to a Broader Term).
- Attributed (The ICD10 code is attributed by Orphanet).</obo:ECO_0000218>
    </owl:Axiom>
```

There are many such lines, and they can be identified by the use of `obo:ECO_0000218`.

What we need to do is: 

- [x] 1. Create a list of all unique `obo:ECO_0000218` annotations with sparql (example query: https://api.triplydb.com/s/EZCOUQGIM)
- [x] 2. Map all the unique values from step (1) to the corresponding long descriptive string (e.g. `NTBT...`)
- [x] 3. Map all the unique values from step (2) (long descriptive string) to a skos:*Match predicate
- [x] 4. Develop a SPARQL update query that matches each instance resembling the pattern above and replaces it with the corresponding skos pattern. Put it in `src/sparql/<name-of-query>.ru`. _(edit: Joe 2022/04/25: I actually did this as a `.ru.jinja2` file, and then I use a Python script to orchestrate everything. It then creates an `.ru` file for every pattern, and runs them all in a single `robot query` command)_
- [x] 5. Update the existing ORDO goal to utilize the new query made in (4). Update it here: https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/mondo-ingest.Makefile#L41. The output of that `make` goal will be `imports/ordo_import.owl`.
- [ ] 6. Create a QC check that prevents unmapped patterns in future versions of ORDO. _(Joe 2022/04/27: Waiting on discussion w/ @matentzn , because it looks like this needs to be added to / used by `Makefile`, but that file gets auto-generated, so I'm not how I should make sure that the `Makefile` uses the new QC check)_
- [x] 7. Need a `make` goal in `mondo-ingest.Makefile` to create `imports/ordo_import.json` from `imports/ordo_import.owl`
- [x] 8. run: `sssom parse imports/ordo_import.json`. Populate `src/ontology/mappings/` with this mapping set, `ordo.sssom.tsv`. (Joe: I suppose I can do this via `sssom parse`
- [ ] 9. Figure out what `W` should map to. currently being mapped to `sssom:notExactMatch`

**Comment by matentzn** [comment]
Pre-requisite for https://github.com/monarch-initiative/mondo/issues/4741

**Comment by joeflack4** [comment]
`NTBT (ORPHA code&apos;s Narrower Term maps to a Broader Term)` == `skos:broadMatch`

**Comment by joeflack4** [comment]
@matentzn Regarding (6), I'm not sure where/how to do the QC check. I think when you say "QC check", this is kind of a standard procedure, so if I learn what it means to do this then I will probably know what to do for future such QC checks.

I looked around, and here's what I think I probably need to do:
1. Create the QC sparql file in `src/sparql`, with name `<qc-check-name>-violation.sparql`.
2. Add the name of the QC check, `<qc-check-name>` (that is, the file name without the `-violation.sparql`) to [SPARQL_VALIDATION_CHECKS](https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/Makefile#L41) in `src/ontology/Makefile`.
3. The QC check should return results if it finds anything problematic; if nothing problematic is found, there should be no results.

From what I can see, these QC checks will run whenever `make test` is run.

**Comment by matentzn** [comment]
This almost exactly right! 

I will do one additional step that is needed.

**Comment by joeflack4** [comment]
@nicolevasilevsky @sabrinatoro @matentzn I compiled a list of the different _ORDO mapping annotation codes_ and their various instances in our `ordo.owl`.

I noticed that it appears that all of these mappings are to ICD10.

Take a look at them, and see if you agree/disagree with the _semantic relationship CURIEs_ I've assigned.
[ordo-icd10-mapping-annotations_relationship-curies.csv](https://github.com/monarch-initiative/mondo-ingest/files/8517991/ordo-icd10-mapping-annotations_relationship-curies.csv)
[ordo-icd10-mapping-annotations.txt](https://github.com/monarch-initiative/mondo-ingest/files/8517992/ordo-icd10-mapping-annotations.txt)
[ordo-mapping-codes_relationship-curies.csv](https://github.com/monarch-initiative/mondo-ingest/files/8517993/ordo-mapping-codes_relationship-curies.csv)

**Comment by matentzn** [comment]
Fantastic work @joeflack4 thats great! 

Questions/notes:

1. So OMIM mappings do not have these strange strings? Only ICD10?
2. Are there any other mappings in ordo other than OMIM and ICD10?
3. `skos:narrower` in your table should be `skos:narrowMatch` (etc)
4. @sabrinatoro from [ordo-icd10-mapping-annotations_relationship-curies.csv](https://github.com/monarch-initiative/mondo-ingest/files/8517991/ordo-icd10-mapping-annotations_relationship-curies.csv), can you figure out what things like "specific code", "index term" etc are supposed to mean (using that ORDO curation guide we found once in the past)? I would in particular like to know if @joeflack4 `ND` mappings are really "related". 
5. @joeflack4 `W` should be skos:exactMatch + `predicate_modifier: Not` I think.

Super excited, super cool.

**Comment by joeflack4** [comment]
Answers: @matentzn 
1. I was surprised to see only ICD10 mentioned in these mapping strings. I wonder if that is an error/typo on the ORDO end or in whatever process is generating `ordo.owl` when I did the `refresh-ordo` command. Looking at `ordo.owl`, there are other mappings, but they are directly on the classes themselves (including both ICD10 and OMIM mappings), as opposed to axiom annotation mappings. I think it's just the case that for some reason that all of the axiom annotation mappings are ICD10 only.
2. Not as axiom annotation mappings. But as far as mappings directly on classes go, I am seeing, at a glance, mappings for: ICD-10, OMIM, UMLS, MedDRA, and MeSH.
3. Ahhh, I see, thank you.
4. Looking at the mapping strings, I can see that `ND` stands for "not determined". I don't know if this means (a) "the terms are related, but it is not determined what relationship exists" or if it means (b) "it is not known yet if the terms are related and, if they are, it is not known what type of relationship it is".
5. I was thinking about that, but I don't know how to do predicate modification in SPARQL or in RDF/OWL. I imagine I can look it up, but if you know off the top of your head, let me know.

**Comment by matentzn** [comment]
1. Dont worry, I think we dont need to concern ourselves about that anymore. Can you mention at next tech call to send a message to orphanet asking about the precision of OMIM, UMLS mappings?
2. Cool.
3. NP.
4. @sabrinatoro is on it (no further action required from you for now)
5. You cant do it in SPARQL, but in SSSOM you can!

**Comment by sabrinatoro** [comment]
For safekeeping: link to Orphanet coding rules: https://www.orpha.net/orphacom/cahiers/docs/GB/Orphanet_ICD10_coding_rules.pdf

**Comment by matentzn** [comment]
Thank you @sabrinatoro :)

**Comment by sabrinatoro** [comment]
from https://www.orpha.net/orphacom/cahiers/docs/GB/Orphanet_ICD10_coding_rules.pdf 
There are 3 types of terms: 
- **Main** : term in orphanet us the same as ICD10, and has its own code
- **Inclusion**: term in orphanet is included in an ICD10 term (either in “synonyms”, “applicable to”,...). There is no specific ICD10 code for this specific orphanet term, but one could find this term by searching it. 
- **Index**: term in orphanet is included in an ICD10 term BUT cannot be found in “synonyms” or “applicable to” (ie someone would need to know that the orphanet term would be found in a specific ICD10 code).  Most of the corresponding ICD10 terms are “~not elsewhere classified” or “other specified disorders of ~”. 

Proximity relationships 
- **Exact:** The Orphanet entity and the ICD-10 code have the same range of application, they describe the same pathological entity
- **BTNT**: (broader term to narrower term): The Orphanet entity has a broader range than the ICD-10 code used to represent it
- **NTBT** (narrower term to broader term): The Orphanet entity has a narrower range than the ICD-10 code used to represent it
- **ND** (not yet decided or unable to decide) is reserved for complex cases when the alignment cannot be qualified by any of the preceding labels

Specificity relationships : 
- **Specific code**: Indicates that the Orphanet entity is matched by an ICD main term that has its own code in ICD-10
- **Inclusion term**: Indicates that the Orphanet entity is matched by an ICD term that does not have its own code, but can be found under this ICD code (e.g. as 'synonyms' or 'applicable to') 
- **Index term:** Indicates that the Orphanet entity is matched by an ICD term that does not have its own code, and cannot be found under the ICD code (eg as 'synonyms' or 'applicable to'). 
- **Attributed code**: Indicates that the Orphanet entity has no matching term at all in ICD-10 and the ICD-10 code of its closest corresponding entity according to Orphanet’s rules is used.

**Comment by sabrinatoro** [comment]
@joeflack4 @matentzn 
I think that the most important information in the manual_assertion annotation (at least for what we are doing) is the "proximity relationships", ie "exact", "broad", "narrow" 
The rest of the information is referring to the specificity to the ICD10 code (which is good to know and understand, but is not affecting the actual mapping). 

Note that the **"ND"** annotation means that nobody has looked at it or reviewed it. It is unclear where the mappings are coming from (probably automated?), so I think these mappings mean "we don't know, use at your own risk". 
I don't know whether we want these mapping at all. IF we want them, I don't know which relation we want to give them since they could be 'anything'. For example: using "related" might be the safest as we wouldn't make a strong assertion of something we don't know, but "related" in Mondo means that "the usage is not strictly correct" which would be incorrect if the actual relation is 'exact' or 'broad' or 'narrow'. (My personal opinion: unless we know exactly where these mappings came from, I would exclude them)

Finally "W" (wrong mapping): In all the examples I looked at, this annotation was attached to an OMIM id. The name in omim is the same (or similar to) the term in orphanet, but the concepts in omim and orphanet are not the same. My guess is that someone reviewed the mappings are realized they were incorrect (but kept them for record). So for our purposes, I think we should ignore them instead of bringing them in. 

Please let me know if you need anything else.

**Comment by matentzn** [comment]
Awesome, thanks for collecting that info @sabrinatoro. I think I need some clarity during the QC call today, especially around phrases like "ICD term that does not have its own code". Can you add to QC agenda?
