### ISSUE TITLE
Make sure `slurp/omim.tsv` contains `OMIMPS`

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#246]
## Sub-tasks
- [x] 1. Make sure `slurp/omim.tsv` contains `OMIMPS`
- [x] 2. Make sure that terms that do not have any parents are actually slurped

**Comment by joeflack4** [comment]
It looks like the issue in sub-task (2) was the cause of the issue in sub-task (1). #252 should fix the issue.
