### ISSUE TITLE
Make sure all OMIMPs terms have to have children

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#279]
See https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/slurp/omim.tsv

E.g. [congenital myopathy 123](https://omim.org/entry/619967) (`OMIM:619967`)should be child of its phenotypic series, but is not

**Comment by joeflack4** [comment]
Made progress on this on Saturday. Should be able to pick up on this / complete it this Wednesday or Thursday.
