### ISSUE TITLE
Bug with exclusions - something related to oak?

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#295]
```
python3 ../scripts/mirror_signature_via_oak.py --db-path components/ncit.db --onto-config-path metadata/ncit.yml --outpath reports/mirror_signature-ncit.tsv;\

Traceback (most recent call last):
  File "/work/src/ontology/../scripts/mirror_signature_via_oak.py", line 13, in <module>
    from oaklib import get_implementation_from_shorthand
  File "/usr/local/lib/python3.10/dist-packages/oaklib/__init__.py", line 7, in <module>
    from oaklib.interfaces import BasicOntologyInterface  # noqa:F401
  File "/usr/local/lib/python3.10/dist-packages/oaklib/interfaces/__init__.py", line 1, in <module>
    from oaklib.interfaces.basic_ontology_interface import BasicOntologyInterface
  File "/usr/local/lib/python3.10/dist-packages/oaklib/interfaces/basic_ontology_interface.py", line 12, in <module>
    from sssom.parsers import parse_sssom_table, to_mapping_set_document
  File "/usr/local/lib/python3.10/dist-packages/sssom/__init__.py", line 18, in <module>
    from .util import (  # noqa:401
  File "/usr/local/lib/python3.10/dist-packages/sssom/util.py", line 77, in <module>
    from .context import (
  File "/usr/local/lib/python3.10/dist-packages/sssom/context.py", line 8, in <module>
    from linkml.generators.jsonldcontextgen import ContextGenerator
  File "/usr/local/lib/python3.10/dist-packages/linkml/__init__.py", line 4, in <module>
    import rdflib_shim
  File "/usr/local/lib/python3.10/dist-packages/rdflib_shim/__init__.py", line 20, in <module>
    if __version__.startswith("6."):
AttributeError: 'NoneType' object has no attribute 'startswith'
make[3]: *** [mondo-ingest.Makefile:356: reports/mirror_signature-ncit.tsv] Error 1
make[3]: Leaving directory '/work/src/ontology'
make[2]: *** [mondo-ingest.Makefile:238: exclusions-ncit] Error 2
make[2]: Leaving directory '/work/src/ontology'
make[1]: *** [mondo-ingest.Makefile:243: exclusions-all] Error 2
make[1]: Leaving directory '/work/src/ontology'
make: *** [mondo-ingest.Makefile:301: build-mondo-ingest] Error 2
Command exited with non-zero status 2
### DEBUG STATS ###
Elapsed time: 1:00:20
Peak memory: 16711620 kb
```

**Comment by matentzn** [comment]
We should probably make it a requirement to run the whole pipeline before merging, but I wonder if it would have been possible to catch this.

**Comment by joeflack4** [comment]
Looks like the crux of it is:
```
  File "/usr/local/lib/python3.10/dist-packages/rdflib_shim/__init__.py", line 20, in <module>
    if __version__.startswith("6."):
```

@matentzn I'm guessing you mean merging some recent PR. I don't think it's related to any recent work. I am thinking our pipeline is set to install a non-fixed version of OAK. We'll probably want to fix it to a version of OAK that doesn't import whatever version of `rdflib_shim` has this bug.

I'll see if I can fix the OAK version for now and likely open up a mirror issue over at OAK as well.

**Comment by joeflack4** [comment]
@matentzn Update today. I had no problem running it on the `obolibrary/odkfull:dev`, which is using `oaklib==0.1.71` from what I can see. I also had no problem running it locally with my current version of `oaklib==0.2.7`.

I see that the latest version on PyPi is `0.5.4` though. I'm supposing your version is newer because you are running this outside of a container on your server with non-fixed version of OAK.

I think I should make 1 or more issues somewhere about this. It appears that `from oaklib import get_implementation_from_shorthand` raises an error in your version of OAK in whatever environment you were running. But this also looks like an issue for certain versions of `sssom` and `linkml`; whichever ones are running that version of `rdflib_shim`, which appears to be where the error is coming from.

**Comment by matentzn** [comment]
Yes confirmed - the problem was caused by some (temporary?) incompatibility between oak and sssom, I tried it again now and it ran through. Will reopen if error re emerges. Thanks for investigating.
