### ISSUE TITLE
OMIM: i. Adhere to basic principles for all source ingests, ii. ensure slurp

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#3]
- [ ] Create a basic version of the OMIM ontology according to the specs outlined in #2 
- [ ] Ensure the old slurping pipeline still works ([issue](https://github.com/monarch-initiative/mondo/issues/3683))

**Comment by joeflack4** [comment]
@matentzn Received. I should be able to work on this in the next week!

**Comment by matentzn** [comment]
This is no longer needed. New pipeline imminent.
