### ISSUE TITLE
Create a private fork for Mondo Ingest

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#302]
For some terminologies with licensing issues, we should provide a private fork.

This should literally be a fork that can be kept up to date wrt to most functionality, so we need to think about an appropriate org for this.

**Comment by joeflack4** [comment]
I remember us talking about this. Will do.

**Comment by joeflack4** [comment]
@matentzn I was going to start on this, but what do you prefer?
a. We can create it inside of `monarch-initiative`, but we will have to configure the public repository as another git remote locally (I think we would have to do that anyway), And we wouldn't have any fork-related UI in GitHub. But unless you're making a pull request back to the original repository, we are not really missing out on very much.
b. We can fork it to a different organization. I could fork it to HOT-Ecosystem, or we could make another random organization, like monarch-initiative-private.

**Comment by matentzn** [comment]
Very good question. Maybe fork at first to your personal account if you don't mind, and we will sort out the final destination later

**Comment by joeflack4** [comment]
@matentzn Just tried that and, welp, looks like we're stuck with 'a':
<img width="796" alt="Screen Shot 2023-05-21 at 3 38 32 PM" src="https://github.com/monarch-initiative/mondo-ingest/assets/13045020/d27329fb-af41-41a9-b016-b06fa817f79c">
