### ISSUE TITLE
Incorporate rejected mappings in pipeline

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#304]
1. Include a `make` goal that clones the rejected mappings from @sabrinatoro TSV in `../mappings/rejected.sssom.tsv`.
2. Incorporated rejected mappings  by removing all matched rows where subject_id, predicate_id, object_id (nothing else) are in the rejected mappings

@hrshdhgd says there is already a function for that

**Comment by hrshdhgd** [comment]
There doesn't seem to be a `../mappings/rejected.sssom.tsv` in the [mappings dir](https://github.com/monarch-initiative/mondo-ingest/tree/main/src/mappings)

**Comment by matentzn** [comment]
No, you have to reach out to Sabrina to get the Google sheet url and then wget it from there

**Comment by sabrinatoro** [comment]
@hrshdhgd and @matentzn 
Is this what you need? 
https://docs.google.com/spreadsheets/d/1_Y7zQSOgmrWCPbcz2LkesH1OwtIgyqXDpshMEc_pMmQ/edit#gid=0

**Comment by matentzn** [comment]
Almost: you have to manually change the predicate_id column to `skos:exactMatch`, that's all!
