### ISSUE TITLE
Bug: `make mondo.sssom.tsv`: `FileNotFoundError`

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/mondo-ingest#310]
## Overview
I was running `slurp-ordo`, and I got a strange error that I think is coming from `sssom-py`:

```
sssom parse tmp/mirror-mondo.json --no-strict-clean-prefixes -I obographs-json -m metadata/mondo.sssom.config.yml -C merged -o tmp/mondo.sssom.tsv
Traceback (most recent call last):
  File "/usr/local/bin/sssom", line 5, in <module>
    from sssom.cli import main
  File "/usr/local/lib/python3.10/dist-packages/sssom/cli.py", line 98, in <module>
    default=os.getcwd(),
FileNotFoundError: [Errno 2] No such file or directory
```

Here's the full log:
<details><summary>Details</summary>
<p>

sh run.sh make IMP=false COMP=false MIR=false slurp-ordo
Running  with -Xmx20G of memory for ROBOT and Java-based pipeline steps.
make: Entering directory '/work/src/ontology'
mondo-ingest.Makefile:34: warning: overriding recipe for target 'components/omim.owl'
Makefile:379: warning: ignoring old recipe for target 'components/omim.owl'
mondo-ingest.Makefile:48: warning: overriding recipe for target 'components/ordo.owl'
Makefile:390: warning: ignoring old recipe for target 'components/ordo.owl'
mondo-ingest.Makefile:67: warning: overriding recipe for target 'components/ncit.owl'
Makefile:401: warning: ignoring old recipe for target 'components/ncit.owl'
mondo-ingest.Makefile:77: warning: overriding recipe for target 'components/doid.owl'
Makefile:412: warning: ignoring old recipe for target 'components/doid.owl'
mondo-ingest.Makefile:99: warning: overriding recipe for target 'component-download-icd10cm.owl'
Makefile:419: warning: ignoring old recipe for target 'component-download-icd10cm.owl'
mondo-ingest.Makefile:104: warning: overriding recipe for target 'components/icd10cm.owl'
Makefile:423: warning: ignoring old recipe for target 'components/icd10cm.owl'
mondo-ingest.Makefile:118: warning: overriding recipe for target 'components/icd10who.owl'
Makefile:434: warning: ignoring old recipe for target 'components/icd10who.owl'
mondo-ingest.Makefile:132: warning: overriding recipe for target 'mondo-ingest-full.owl'
Makefile:560: warning: ignoring old recipe for target 'mondo-ingest-full.owl'
mondo-ingest.Makefile:506: warning: overriding recipe for target 'help'
Makefile:631: warning: ignoring old recipe for target 'help'
make slurp/ordo.tsv -B
make[1]: Entering directory '/work/src/ontology'
mondo-ingest.Makefile:34: warning: overriding recipe for target 'components/omim.owl'
Makefile:379: warning: ignoring old recipe for target 'components/omim.owl'
mondo-ingest.Makefile:48: warning: overriding recipe for target 'components/ordo.owl'
Makefile:390: warning: ignoring old recipe for target 'components/ordo.owl'
mondo-ingest.Makefile:67: warning: overriding recipe for target 'components/ncit.owl'
Makefile:401: warning: ignoring old recipe for target 'components/ncit.owl'
mondo-ingest.Makefile:77: warning: overriding recipe for target 'components/doid.owl'
Makefile:412: warning: ignoring old recipe for target 'components/doid.owl'
mondo-ingest.Makefile:99: warning: overriding recipe for target 'component-download-icd10cm.owl'
Makefile:419: warning: ignoring old recipe for target 'component-download-icd10cm.owl'
mondo-ingest.Makefile:104: warning: overriding recipe for target 'components/icd10cm.owl'
Makefile:423: warning: ignoring old recipe for target 'components/icd10cm.owl'
mondo-ingest.Makefile:118: warning: overriding recipe for target 'components/icd10who.owl'
Makefile:434: warning: ignoring old recipe for target 'components/icd10who.owl'
mondo-ingest.Makefile:132: warning: overriding recipe for target 'mondo-ingest-full.owl'
Makefile:560: warning: ignoring old recipe for target 'mondo-ingest-full.owl'
mondo-ingest.Makefile:506: warning: overriding recipe for target 'help'
Makefile:631: warning: ignoring old recipe for target 'help'
mkdir -p tmp
if [ false = true ] && [ false = true ]; then robot --catalog catalog-v001.xml merge -I http://www.orphadata.org/data/ORDO/ordo_orphanet.owl \
annotate --ontology-iri http://purl.obolibrary.org/obo/mondo-ingest/component-download-ordo.owl annotate -V http://purl.obolibrary.org/obo/mondo-ingest/releases/2023-05-16/component-download-ordo.owl --annotation owl:versionInfo 2023-05-16 -o tmp/component-download-ordo.owl.owl; fi
if [ false = true ]; then robot --catalog catalog-v001.xml query -i tmp/component-download-ordo.owl.owl --update ../sparql/ordo-construct-subclass-from-part-of.ru \
	query -q "../sparql/ordo-relevant-signature.sparql" tmp/ordo_relevant_signature.txt; fi
if [ false = true ]; then robot --catalog catalog-v001.xml remove -i tmp/component-download-ordo.owl.owl --select imports \
	merge \
	rename --mappings config/property-map-1.sssom.tsv --allow-missing-entities true \
	rename --mappings config/property-map-2.sssom.tsv --allow-missing-entities true \
	query \
		--update ../sparql/fix_partof.ru \
		--update ../sparql/fix_deprecated.ru \
		--update ../sparql/fix_complex_reification.ru \
		--update ../sparql/fix_xref_prefixes.ru \
		--update ../sparql/fix-labels-with-brackets.ru \
		--update ../sparql/ordo-construct-subclass-from-part-of.ru \
		--update ../sparql/ordo-construct-subsets.ru \
		--update ../sparql/ordo-construct-d2g.ru \
		--update ../sparql/ordo-replace-annotation-based-mappings.ru \
	filter -T tmp/ordo_relevant_signature.txt --trim false \
	remove -T config/properties.txt --select complement --select properties --trim true \
	annotate --ontology-iri http://purl.obolibrary.org/obo/mondo/sources/ordo.owl --version-iri http://purl.obolibrary.org/obo/mondo/sources/2023-05-16/ordo.owl -o components/ordo.owl; fi
if [ false = true ]; then wget http://purl.obolibrary.org/obo/mondo.owl -O tmp/mondo.sssom.tsv; else cd tmp &&\
	rm -rf ./mondo/ &&\
	git clone --depth 1 https://github.com/monarch-initiative/mondo &&\
	cd mondo/src/ontology &&\
	make mondo.owl mappings -B MIR=false IMP=false MIR=false &&\
	cd ../../../../ &&\
	cp tmp/mondo/src/ontology/mondo.owl tmp/mondo.sssom.tsv &&\
	cp tmp/mondo/src/ontology/mappings/mondo.sssom.tsv tmp/mondo.sssom.tsv &&\
	rm -rf tmp/mondo/; fi
Cloning into 'mondo'...
remote: Enumerating objects: 1198, done.
remote: Counting objects: 100% (1198/1198), done.
remote: Compressing objects: 100% (876/876), done.
remote: Total 1198 (delta 475), reused 752 (delta 300), pack-reused 0
Receiving objects: 100% (1198/1198), 57.35 MiB | 3.43 MiB/s, done.
Resolving deltas: 100% (475/475), done.
Updating files: 100% (1239/1239), done.
make[2]: Entering directory '/work/src/ontology/tmp/mondo/src/ontology'
perl -ne 'print unless (m@^xref: (Orphanet|OMIM|OMIMPS|DOID|EFO|NCIT|SCTID|MESH|UMLS|ICD10CM):@ && !(m@(obsoleteEquivalent|equivalentObsolete|equivalentTo|relatedTo|mondoIsNarrowerThanSource|directSiblingOf|mondoIsBroaderThanSource)@i))' mondo-edit.obo | grep -v '^property_value: confidence' | grep -v '^property_value: excluded_subClassOf' | egrep -v '^synonym: .*EXCLUDE' | egrep -v 'relationship: disease_has_basis_in_dysfunction_of (hgnc|HGNC|NCBIGene):' > filtered.obo.tmp && mv filtered.obo.tmp filtered.obo
if [ false = false ]; then robot --catalog catalog-v001.xml query -i filtered.obo --use-graphs false \
	--update ../sparql/update/delete-axiom-annotations.ru \
	--update ../sparql/update/delete-axiom-annotations-by-prefix.ru \
	remove --term-file config/remove-annotations-before-release.txt \
	convert -f obo --check false -o filtered.obo.obo && mv filtered.obo.obo filtered.obo; fi
../utils/mk-skos.pl filtered.obo > skos.ttl
owltools --use-catalog filtered.obo  skos.ttl --merge-support-ontologies -o filtered.owl
adding support ont Ontology(OntologyID(Anonymous-49)) [Axioms: 74870 Logical Axioms: 0] First 20 axioms: {AnnotationAssertion(<http://www.w3.org/2004/02/skos/core#exactMatch> <http://purl.obolibrary.org/obo/MONDO_0016657> <http://linkedlifedata.com/resource/umls/id/C4304505>) AnnotationAssertion(<http://www.w3.org/2004/02/skos/core#exactMatch> <http://purl.obolibrary.org/obo/MONDO_0021944> <http://linkedlifedata.com/resource/umls/id/C2732267>) AnnotationAssertion(<http://www.w3.org/2004/02/skos/core#exactMatch> <http://purl.obolibrary.org/obo/MONDO_0007571> <http://www.orpha.net/ORDO/Orphanet_90026>) AnnotationAssertion(<http://www.w3.org/2004/02/skos/core#exactMatch> <http://purl.obolibrary.org/obo/MONDO_0032914> <https://omim.org/entry/618781>) AnnotationAssertion(<http://www.w3.org/2004/02/skos/core#exactMatch> <http://purl.obolibrary.org/obo/MONDO_0008153> <http://purl.obolibrary.org/obo/DOID_0111535>) AnnotationAssertion(<http://www.w3.org/2004/02/skos/core#exactMatch> <http://purl.obolibrary.org/obo/MONDO_0100325> <http://identifiers.org/snomedct/717823001>) AnnotationAssertion(<http://www.w3.org/2004/02/skos/core#exactMatch> <http://purl.obolibrary.org/obo/MONDO_0033005> <https://omim.org/entry/251300>) AnnotationAssertion(<http://www.w3.org/2004/02/skos/core#exactMatch> <http://purl.obolibrary.org/obo/MONDO_0012658> <http://www.orpha.net/ORDO/Orphanet_140908>) AnnotationAssertion(<http://www.w3.org/2004/02/skos/core#exactMatch> <http://purl.obolibrary.org/obo/MONDO_0000471> <http://purl.obolibrary.org/obo/NCIT_C78649>) AnnotationAssertion(<http://www.w3.org/2004/02/skos/core#closeMatch> <http://purl.obolibrary.org/obo/MONDO_0006680> <http://identifiers.org/meddra/10062788>) AnnotationAssertion(<http://www.w3.org/2004/02/skos/core#exactMatch> <http://purl.obolibrary.org/obo/MONDO_0006047> <http://identifiers.org/snomedct/700423003>) AnnotationAssertion(<http://www.w3.org/2004/02/skos/core#exactMatch> <http://purl.obolibrary.org/obo/MONDO_0016320> <http://www.orpha.net/ORDO/Orphanet_217454>) AnnotationAssertion(<http://www.w3.org/2004/02/skos/core#exactMatch> <http://purl.obolibrary.org/obo/MONDO_0015678> <http://www.orpha.net/ORDO/Orphanet_168621>) AnnotationAssertion(<http://www.w3.org/2004/02/skos/core#exactMatch> <http://purl.obolibrary.org/obo/MONDO_0017339> <http://linkedlifedata.com/resource/umls/id/C1838440>) AnnotationAssertion(<http://www.w3.org/2004/02/skos/core#exactMatch> <http://purl.obolibrary.org/obo/MONDO_0014741> <http://linkedlifedata.com/resource/umls/id/CN242167>) AnnotationAssertion(<http://www.w3.org/2004/02/skos/core#exactMatch> <http://purl.obolibrary.org/obo/MONDO_0012873> <http://linkedlifedata.com/resource/umls/id/C2676510>) AnnotationAssertion(<http://www.w3.org/2004/02/skos/core#exactMatch> <http://purl.obolibrary.org/obo/MONDO_0013018> <http://linkedlifedata.com/resource/umls/id/C2748527>) AnnotationAssertion(<http://www.w3.org/2004/02/skos/core#closeMatch> <http://purl.obolibrary.org/obo/MONDO_0015882> <http://identifiers.org/meddra/10061902>) AnnotationAssertion(<http://www.w3.org/2004/02/skos/core#exactMatch> <http://purl.obolibrary.org/obo/MONDO_0011819> <http://purl.obolibrary.org/obo/DOID_0050970>) AnnotationAssertion(<http://www.w3.org/2004/02/skos/core#exactMatch> <http://purl.obolibrary.org/obo/MONDO_0006476> <http://linkedlifedata.com/resource/umls/id/C0279653>) }
robot --catalog catalog-v001.xml reason -T true -x true -X true -i filtered.owl -r ELK relax reduce -p false -r ELK \
	remove --term MONDO:0700097 annotate -V http://purl.obolibrary.org/obo/mondo/releases/`date +%Y-%m-%d`/reasoned.owl.owl -o reasoned.owl
robot --catalog catalog-v001.xml merge -i reasoned.owl annotate -V http://purl.obolibrary.org/obo/mondo/releases/`date +%Y-%m-%d`/mondo.owl -o mondo.owl
robot merge -i mondo.owl convert -f json -o tmp/mirror-mondo.json
curl https://github.com/monarch-initiative/mondo-ingest/releases/latest/download/mondo-ingest.owl -L --output tmp/mondo-ingest.owl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--  0  188M    0 1439k    0     0   818k      0  0:03:55  0:00:01  0:03  3  188M    3 7136k    0     0  2573k      0  0:01:14  0:00:02  0:01 10  188M   10 20.2M    0     0  5472k      0  0:00:35  0:00:03  0:00 19  188M   19 35.9M    0     0  7586k      0  0:00:25  0:00:04  0:00 26  188M   26 49.2M    0     0  8597k      0  0:00:22  0:00:05  0:00 30  188M   30 56.7M    0     0  8557k      0  0:00:22  0:00:06  0:00 32  188M   32 62.1M    0     0  8201k      0  0:00:23  0:00:07  0:00 37  188M   37 69.7M    0     0  8105k      0  0:00:23  0:00:08  0:00 40  188M   40 76.2M    0     0  7976k      0  0:00:24  0:00:09  0:00 46  188M   46 86.9M    0     0  8273k      0  0:00:23  0:00:10  0:00 49  188M   49 92.7M    0     0  7756k      0  0:00:24  0:00:12  0:00 52  188M   52 98.4M    0     0  7865k      0  0:00:24  0:00:12  0:00 57  188M   57  108M    0     0  7985k      0  0:00:24  0:00:13  0:00 61  188M   61  116M    0     0  8062k      0  0:00:23  0:00:14  0:00 65  188M   65  124M    0     0  8072k      0  0:00:23  0:00:15  0:00 70  188M   70  133M    0     0  8134k      0  0:00:23  0:00:16  0:00 77  188M   77  146M    0     0  8437k      0  0:00:22  0:00:17  0:00 85  188M   85  160M    0     0  8717k      0  0:00:22  0:00:18  0:00 87  188M   87  165M    0     0  8522k      0  0:00:22  0:00:19  0:00 94  188M   94  178M    0     0  8802k      0  0:00:21  0:00:20  0:00100  188M  100  188M    0     0  8986k      0  0:00:21  0:00:21 --:--:-- 11.7M

RUST_BACKTRACE=full semsql make tmp/mondo-ingest.db -P config/prefixes.csv
make[3]: Entering directory '/work/src/ontology/tmp/mondo/src/ontology'
robot \
  remove -i tmp/mondo-ingest.owl --axioms "equivalent disjoint annotation" \
  filter --exclude-terms /usr/local/lib/python3.10/dist-packages/semsql/builder//exclude-terms.txt \
  -o tmp/mondo-ingest-min.owl
touch tmp/mondo-ingest-properties.txt
grep -v ^prefix, config/prefixes.csv | grep -v ^obo, | perl -npe 's@,(.*)@: "$1"@'  > tmp/mondo-ingest-prefixes.yaml.tmp && mv tmp/mondo-ingest-prefixes.yaml.tmp tmp/mondo-ingest-prefixes.yaml
relation-graph --disable-owl-nothing true \
                       --ontology-file tmp/mondo-ingest-min.owl\
	        \
                       --output-file tmp/mondo-ingest-relation-graph.tsv.tmp \
                       --equivalence-as-subclass true \
                       --mode TSV \
	       --prefixes tmp/mondo-ingest-prefixes.yaml \
               --output-individuals true \
               --output-subclasses true \
                       --reflexive-subclasses true && \
mv tmp/mondo-ingest-relation-graph.tsv.tmp tmp/mondo-ingest-relation-graph.tsv
2023.05.16 23:07:54:832 zio-default-blocking-1 INFO org.renci.relationgraph.RelationGraph$
    Running reasoner
2023.05.16 23:08:12:839 zio-default-blocking-1 INFO org.renci.relationgraph.RelationGraph$
    Done running reasoner
2023.05.16 23:09:53:784 ZScheduler-1 INFO org.renci.relationgraph.Main.program:40
    Done computing relations
rm -f tmp/mondo-ingest.db.tmp && \
cat /usr/local/lib/python3.10/dist-packages/semsql/builder//sql_schema/semsql.sql | sqlite3 tmp/mondo-ingest.db.tmp && \
echo .exit | sqlite3 -echo tmp/mondo-ingest.db.tmp -cmd ".mode csv" -cmd ".import config/prefixes.csv prefix" && \
rdftab tmp/mondo-ingest.db.tmp < tmp/mondo-ingest.owl && \
sqlite3 tmp/mondo-ingest.db.tmp -cmd '.separator "\t"' ".import tmp/mondo-ingest-relation-graph.tsv entailed_edge" && \
gzip -f tmp/mondo-ingest-relation-graph.tsv && \
cat /usr/local/lib/python3.10/dist-packages/semsql/builder//indexes/*.sql | sqlite3 tmp/mondo-ingest.db.tmp && \
echo "ALTER TABLE statements ADD COLUMN graph TEXT;" | sqlite3 tmp/mondo-ingest.db.tmp && \
mv tmp/mondo-ingest.db.tmp tmp/mondo-ingest.db
.exit

disk I/O error
make[3]: *** [/usr/local/lib/python3.10/dist-packages/semsql/builder/build.Makefile:56: tmp/mondo-ingest.db] Error 1
make[3]: Leaving directory '/work/src/ontology/tmp/mondo/src/ontology'
sssom parse tmp/mirror-mondo.json --no-strict-clean-prefixes -I obographs-json -m metadata/mondo.sssom.config.yml -C merged -o tmp/mondo.sssom.tsv
/usr/local/lib/python3.10/dist-packages/rdflib_jsonld/__init__.py:9: DeprecationWarning: The rdflib-jsonld package has been integrated into rdflib as of rdflib==6.0.0.  Please remove rdflib-jsonld from your project's dependencies.
  warnings.warn(
Traceback (most recent call last):
  File "/usr/local/bin/sssom", line 5, in <module>
    from sssom.cli import main
  File "/usr/local/lib/python3.10/dist-packages/sssom/cli.py", line 98, in <module>
    default=os.getcwd(),
FileNotFoundError: [Errno 2] No such file or directory
make[2]: *** [mondo.Makefile:469: tmp/mondo.sssom.tsv] Error 1

make[2]: Leaving directory '/work/src/ontology/tmp/mondo/src/ontology'
make[1]: *** [mondo-ingest.Makefile:334: tmp/mondo.sssom.tsv] Error 2
make[1]: Leaving directory '/work/src/ontology'
make: *** [mondo-ingest.Makefile:452: slurp-ordo] Error 2
make: Leaving directory '/work/src/ontology'
Command exited with non-zero status 2
### DEBUG STATS ###
Elapsed time: 14:02.20
Peak memory: 7451444 kb

</p>
</details> 

## Additional information
I ran this on `obolibrary/odkfull:dev`. SSSOM dependencies installed are:
```
sssom==0.3.30
sssom-schema==0.11.0
```

**Comment by joeflack4** [comment]
@matentzn @hrshdhgd any thoughts?

@matentzn Also, I don't remember if there was any reason that I/we did this. `slurp-%` runs w/ the force flag: `$(MAKE) slurp/$*.tsv -B`. Do you know / remember why this is? I was thinking `slurp-%` was just an alias for `slurp/%.tsv` but maybe there is a reason for `-B`.

**Comment by matentzn** [comment]
`mkdir tmp`?

**Comment by joeflack4** [comment]
The `tmp` directory exists, so that shouldn't be the issue.

I'm trying to replicate this:
 - #309 

Actually, I am able to replicate it on a fresh clone of `mondo-ingest`.

If I'm using my normal clone of `mondo-ingest` and run `make slurp/ordo.tsv` (doesn't use `-B`), it works fine. If on that clone I run it with `-B`, I get the strange `FileNotFoundError`.

**Comment by matentzn** [comment]
This is so weird! No ideas on my end.

**Comment by joeflack4** [comment]
I'll just close this one anyway. I am running things fine now and not able to replicate. I'll re-open if it pops back up.
