### ISSUE TITLE
`%_mapped_deprecated.robot.tsv` has wrong column

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#328]
in the second column, `A oboInOwl:hasDbXref` instead of `ID` (where, say, the ORDO term is located).

https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/reports/ordo_mapped_deprecated_terms.robot.template.tsv#L2

**Comment by joeflack4** [comment]
@matentzn Closing because I think we fixed this earlier on call: https://github.com/monarch-initiative/mondo-ingest/commit/1e8170ae51a3b2af13296b95ea23eecf4e71e4b4
