### ISSUE TITLE
Bug in `mapped-deprecated` pipeline

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#331]
There are false positives in the mapped deprecated set: https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/reports/doid_mapped_deprecated_terms.robot.template.tsv

All of these are already deprecated in Mondo. It may be necessary to revise the way you obtain the list of the already obsoleted ones!

**Comment by joeflack4** [comment]
Did you mean "mapped-deprecated"? I updated the title from "unmapped".

I just took a look at the script, and it looks like that was something that wasn't considered. It doesn't (a) check Mondo to see if those terms in Mondo are marked obsolete. It just checks (b) if they're mapped in Mondo (in `mondo.sssom.tsv`), and (c) if the term is deprecated in its own ontology. It sounds like I need to add 'a'?

**Comment by matentzn** [comment]
(A) is missing, yes!
