### ISSUE TITLE
mapping based on OMIM exact-match are reported in different files (lex_exact, and lex)

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo-ingest#335]
I am confused about the difference between the following files:unmapped_doid_lex_exact.tsv and unmapped_doid_lex.tsv
Both files report mapping based on exact match with OMIM. For the few I checked, there is no overlapping between these files (which is good), but I don't understand the difference between these files and why some are reported in one file and others are reported in the other file.
The reason I want to understand is that it might mean that I need to pay extra attention to something.
Thanks! 

Examples from unmapped_doid_lex_exact.tsv
subject_id | subject_label | object_id | predicate_id | object_label | mapping_justification | mapping_tool | confidence | subject_match_field | object_match_field | match_string
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
MONDO:0010890 | acrocardiofacial syndrome | DOID:0070419 | MONDO:equivalentTo | acrocardiofacial syndrome | semapv:LexicalMatching | oaklib | 0.9411764706 | skos:exactMatch | skos:exactMatch | omim:600460
MONDO:0011213 | Pierpont syndrome | DOID:0081362 | MONDO:equivalentTo | Pierpont syndrome | semapv:LexicalMatching | oaklib | 0.9411764706 | skos:exactMatch | skos:exactMatch | omim:602342
MONDO:0014940 | neurodegeneration with ataxia, dystonia, and gaze palsy, childhood-onset | DOID:0081364 | MONDO:equivalentTo | neurodegeneration with ataxia, dystonia, and gaze palsy, childhood-onset | semapv:LexicalMatching | oaklib | 0.9411764706 | skos:exactMatch | skos:exactMatch | omim:617145

Examples from unmapped_doid_lex.tsv
subject_id | subject_label | object_id | predicate_id | object_label | mapping_justification | mapping_tool | confidence | subject_match_field | object_match_field | match_string
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
MONDO:0007187 | nevoid basal cell carcinoma syndrome | DOID:0070365 | MONDO:equivalentTo | nevoid basal cell carcinoma syndrome 1 | semapv:LexicalMatching | oaklib | 0.9411764706 | skos:exactMatch | skos:exactMatch | omim:109400
MONDO:0007239 | epidermolytic ichthyosis | DOID:0081358 | MONDO:equivalentTo | epidermolytic hyperkeratosis 1 | semapv:LexicalMatching | oaklib | 0.9411764706 | skos:exactMatch | skos:exactMatch | omim:113800
MONDO:0008055 | myotonia congenita, autosomal dominant | DOID:0081336 | MONDO:equivalentTo | Thomsen disease | semapv:LexicalMatching | oaklib | 0.9411764706 | skos:exactMatch | skos:exactMatch | omim:160800

**Comment by matentzn** [comment]
Logically, both files belong together. The `exact` variant has an additional feature: not only are synonyms/labels/xrefs etc exact matches - on top of that the _label itself is also guaranteed to be exact_. So the reason for having such a rule is simply that you can apply much less care on the `exact` table.

**Comment by sabrinatoro** [comment]
I see... even though it is not reported in the table, the labels are exact in the exact table. And the fact that the omim x-refs also match is just "extra". 
Got it! Thank you!
