### ISSUE TITLE
BUG: rejected mappings somehow fails.

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#341]
```
make[2]: Leaving directory '/work/src/ontology'
test -f components/rejected-mappings.owl || touch components/rejected-mappings.owl
robot --catalog catalog-v001.xml convert -i components/rejected-mappings.owl -f json -o tmp/component-rejected-mappings.json
OBO GRAPH ERROR Could not convert ontology to OBO Graph (see https://github.com/geneontology/obographs)
For details see: http://robot.obolibrary.org/errors#obo-graph-error
Use the -vvv option to show the stack trace.
Use the --help option to see usage information.
make[1]: *** [mondo-ingest.Makefile:173: tmp/component-rejected-mappings.json] Error 1
rm imports/ro_terms_combined.txt
make[1]: Leaving directory '/work/src/ontology'
make: *** [mondo-ingest.Makefile:326: build-mondo-ingest] Error 2
Command exited with non-zero status 2
```

**Comment by hrshdhgd** [comment]
I don't think I have worked on this part of the code. Maybe @joeflack4 ?

**Comment by matentzn** [comment]
These are somehow connected - The google sheets gets downloaded and turned into OWL, which then gets turned into JSON for some reason I don't know?

Right now the pipeline is not running at all because of this..

**Comment by hrshdhgd** [comment]
what command did you run?

**Comment by matentzn** [comment]
I always run the whole pipeline, put from the error message above, I would say:

```
make[1]: *** [mondo-ingest.Makefile:173: tmp/component-rejected-mappings.json] Error 1
```

You can run: 

```
sh run.sh make IMP=false MIR=false PAT=false tmp/component-rejected-mappings.json -B
```

**Comment by hrshdhgd** [comment]
Digging deeper `components/rejected-mappings.owl` is blank and hence this is throwing the error.

**Comment by hrshdhgd** [comment]
I think this may be because `rejected-mappings.sssom.tsv` does not have a prefix map or metadata.

**Comment by hrshdhgd** [comment]
Figured it out! 

So we have make recipe : 
```
$(MAPPINGSDIR)/%.sssom.tsv: $(TMPDIR)/component-%.json metadata/mondo.sssom.config.yml
	sssom parse $< -I obographs-json --prefix-map-mode merged -m metadata/mondo.sssom.config.yml -o $@
	sssom sort $@ -o $@
```

which has nothing to do with rejected mappings. I had the target `$(MAPPINGSDIR)/rejected-mappings.sssom.tsv` which executed the above and hence the error seen above.

I renamed it to `$(MAPPINGSDIR)/rejected-mappings-sssom.tsv` and this should fix the problem.
