### ISSUE TITLE
OMIMPS terms in "unmapped" tables have no labels

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#350]
See https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/reports/omim_unmapped_terms.tsv

**Comment by joeflack4** [comment]
Uhoh! Setting medium priority, but will look into this weekend. 

I did an initial investigation, and was surprised to see that the most proximal source of the problem is that `components/omim.yml` does not include any OMIMPS terms. Will need to fix the root of the problem for that.

**Comment by joeflack4** [comment]
I was wrong. Was not `components/omim.owl`. For some reason, for several artefacts I was searching, for the same search string, sometimes it showed no results, and other times it showed results.

Problem explained: [here](https://github.com/monarch-initiative/mondo-ingest/pull/351#discussion_r1281190512)

**Comment by matentzn** [comment]
Thank you for investigating!
