### ISSUE TITLE
`lexmatch` is missing umapped_ordo tables

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#353]
For some reason the ordo lexmatch table is missing.

https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/slurp/ordo.tsv#L60

- perrault syndrome type 1 should have been a lexmatch (same exact synonym)

@hrshdhgd high priority issue

Is it somehow possible to create an empty file if there are no matches, and not let it disappear?

I assume this is some kind of prefix mismatch again.

**Comment by matentzn** [comment]
Please also check the following files:

src/ontology/reports/ordo_mapped_deprecated_terms.robot.template.tsv
src/ontology/reports/ordo_unmapped_terms.tsv
docs/reports/unmapped_ordo.md

**Comment by hrshdhgd** [comment]
Could something from [this commit](https://github.com/monarch-initiative/mondo-ingest/commit/47acb634be73568c82708c54b9ff6baf0755f8d7) be responsible?

**Comment by matentzn** [comment]
How? It does not affect Ordo/orphanet as far as I can see?

**Comment by hrshdhgd** [comment]
Oops! I mistook `OMIMPS` for `ORDO`

**Comment by matentzn** [comment]
Will you try to rerun and see if the problem lies with merged.db or mondo.sssom.tsv perhaps?

**Comment by hrshdhgd** [comment]
It was correct until [release 25.07.2023](https://github.com/monarch-initiative/mondo-ingest/commit/f93dfc5c85da588dcdc0086168f1aef74377ab61) It changed in [release 2023-08-20](https://github.com/monarch-initiative/mondo-ingest/commit/a5bc5c5a75a8d59c6d8b075ecb523ff4258308f8)

**Comment by matentzn** [comment]
Iiiiiiii!!!!! tHaaaanks! I will fix it.

**Comment by matentzn** [comment]
Ok, now that I see this; why is this specific file you sent relevant (the ordo.sssom.tsv)? Lexmatch does not really care about that file? Is the prefix changes in mondo-ingest.db?

**Comment by matentzn** [comment]
@hrshdhgd can you try and make sure that our internal prefixmap always takes precedence over the SSSOM py one?

**Comment by hrshdhgd** [comment]
I think it already does that.

**Comment by matentzn** [comment]
But why is the Ordo file empty then if we provide an override for the prefix?

**Comment by hrshdhgd** [comment]
Ok, here's what I found:

The incorrect prefix occurs in 
- gard.sssom.tsv
- omim.sssom.tsv
- ordo.sssom.tsv

I'm going tore`make` these file and run the whole pipeline again. Hope fully that should fix it.

**Comment by hrshdhgd** [comment]
My wild guess is `make mappings` was not run properly when it should have been. It seems to remove all references of `orphaned.ordo` from the entire project.
