### ISSUE TITLE
Automatically update exact synonyms in Mondo

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#355]
Create a GitHub Action in mondo (not mondo-ingest!) that runs once per week, and does the following:

0. (just thought of this, maybe easier) Provide a  merged version of lexmatch/*_exact.robot.tsv (lexmatch/all_exact.robot.tsv)
1. pull lexmatch/all_exact.robot.tsv from mondo-ingest repo using the `make TEMPLATE_URL... merge_template` workflow in `src/ontology/mondo.Makefile`. 
1. Make PR and assign to Sabrine

**Comment by hrshdhgd** [comment]
>Provide a merged version of lexmatch/*_exact.robot.tsv (lexmatch/all_exact.robot.tsv)

Which of the following do you mean :
 - [ ]  `lexmatch/split-mapping-set/mondo_exactmatch_xxxx.tsv` OR
 - [ ] `lexmatch/mondo-only/unmapped_xxxx_mondo_exact.tsv` (All of these are empty).
 - [ ] `lexmatch/unmapped_xxxx_lex_exact.tsv`

**Comment by hrshdhgd** [comment]
Mondo PR: https://github.com/monarch-initiative/mondo/pull/6583

**Comment by matentzn** [comment]
My guess it somehow does not make it in merged.db?

**Comment by joeflack4** [comment]
@matentzn Just curious what is the purpose of this pattern?
```make
MERGE_TEMPLATE=tmp/merge_template.tsv
TEMPLATE_URL=https://docs.google.com/spreadsheets/d/e/2PACX-1vTsgIbFYWkhMT0EgaBNbyT6fJiNKqVjdqcZxXQLwJ3CpXpSzB24BITZGDNSMyg_3bneIvE3F2l_iHWH/pub?gid=1886610709&single=true&output=tsv

tmp/merge_template.tsv:
	wget "$(TEMPLATE_URL)" -O $@

merge_template: $(MERGE_TEMPLATE)
```

Isn't this easier to read?
```make
tmp/merge_template.tsv:
	wget "https://docs.google.com/spreadsheets/d/e/2PACX-1vTsgIbFYWkhMT0EgaBNbyT6fJiNKqVjdqcZxXQLwJ3CpXpSzB24BITZGDNSMyg_3bneIvE3F2l_iHWH/pub?gid=1886610709&single=true&output=tsv" -O $@

merge_template: tmp/merge_template.tsv
```

I don't see these variables being re-used throughout the makefile. Is it this way just for a general programming practice of setting strings (of resources) as variables before using them?

**Comment by joeflack4** [comment]
@matentzn Sorry to derail a little here. I was just looking at the lexmatch a bit deeper to better evaluate #356.

I consulted the docs for `match_string`:
[match_string](https://mapping-commons.github.io/sssom/match_string/)	Strings that are shared by subj/obj. It is recommended to indicate the fields for the match using the object and subject_match_field slots.

Does it mean to say "strings" or should it say "string"? If so, should the field have been called `match_strings`?

If it is supposed to be "strings", should it also not say "_a list of_ strings" to be clearer? E.g. as in `mappings`:
> [mappings](https://mapping-commons.github.io/sssom/mappings/)	Contains _a list of_ mapping objects

Also, should we not say what the delimiter should be? I'm assuming `|`. I couldn't find anything about list delimiters in [the SSSOM docs](https://mapping-commons.github.io/sssom/home/).

Let me know if you want me to open an issue about 1 or more of these things in SSSOM repo.

**Comment by matentzn** [comment]
> @matentzn Just curious what is the purpose of this pattern?

We use it to dynamically run template merges like https://github.com/monarch-initiative/mondo/pull/6583/files#r1302872406

```
make GITHUB_ACTION=true IMP=false PAT=false TEMPLATE_URL="https://raw.githubusercontent.com/monarch-initiative/mondo-ingest/main/src/ontology/lexmatch/all_exact.robot.tsv" merge_template -B
```

> Does it mean to say "strings" or should it say "string"? If so, should the field have been called match_strings?

`match_string` is correct, and for a single match, there should be only 1! If you have multiple matches you should supply multiple justifications!

**Comment by joeflack4** [comment]
Ahh, I see now how these variables allows you to do things dynamically.

RE `match_string`: Fair enough. Then it sounds to me like this should say "String that is shared..." rather than "strings". If I'm wrong then I must be confused, but no big deal.
> [match_string](https://mapping-commons.github.io/sssom/match_string/)	Strings that are shared by subj/obj. It is recommended to indicate the fields for the match using the object and subject_match_field slots.

**Comment by matentzn** [comment]
@joeflack4 you can make a PR at SSSOM to that end (sssom-schema.yml), I think you are right, "string" is better.

**Comment by joeflack4** [comment]
Sure thing!
