### ISSUE TITLE
Problem with GARD subset

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo-ingest#364]
I ran a "mock release", and there is an error with the GARD subset. 

robot --catalog catalog-v001.xml template --template subsets/gard-subset.template.tsv convert -f ttl -o tmp/gard-rare-subset.ttl
UNKNOWN TEMPLATE ERROR could not interpret template string "ID,TYPE,A oboInOwl:hasDbXref,>A oboInOwl:source,AI oboInOwl:inSubset" for column 0 ("mondo_id,type,gard_id,source_external,subset") in table "subsets/gard-subset.template.tsv".
For details see: http://robot.obolibrary.org/template#unknown-template-error
Use the -vvv option to show the stack trace.
Use the --help option to see usage information.
make: *** [mondo.Makefile:230: tmp/gard-rare-subset.ttl] Error 1

Looking at the newly created file: src/ontology/subsets/gard-subset.template.tsv
The file has commas instead of different columns (see screen shot): 
![Screenshot 2023-09-11 at 13 04 18](https://github.com/monarch-initiative/mondo-ingest/assets/12737987/ad32bd36-b27a-4548-b12d-05106ae561f8)

Note: this happened when I did the first step of the release: 
MEMORY_GB=12 sh run.sh make IMP=false all -B

**Comment by sabrinatoro** [comment]
@joeflack4, this is extremely urgent (we need to release hopefully tomorrow). 
Thank you for looking into this. 

(tagging @matentzn as a FYI)

**Comment by joeflack4** [comment]
@sabrinatoro I addressed this with: https://github.com/monarch-initiative/gard/pull/19 and https://github.com/monarch-initiative/mondo/pull/6637

I need @nicolevasilevsky to approve the PR in order to merge to `master`. I tried to circumvent by doing this locally but it still wouldn't let me.

**Comment by joeflack4** [comment]
@matentzn I wonder if this issue is still relevant either.

**Comment by matentzn** [comment]
This had been solved!
