### ISSUE TITLE
MedGen: 278 direct mappings absent from source

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/mondo-ingest#366]
## Overview
Recently, we addressed a situation in which many MedGen/UMLS mappings were bad ([Issue](https://github.com/monarch-initiative/mondo-ingest/issues/273), [PR](https://github.com/monarch-initiative/mondo/pull/6560)). These mappings were identified by Megan Kane, and she made suggestions for new mappings. However, out of those new mappings, 278 of them ([file](https://github.com/monarch-initiative/mondo-ingest/files/12581005/medgen-mondo.matches.in.megans.conflicts.file.but.not.in.MedGenIDMappings.txt), [comment](https://github.com/monarch-initiative/mondo/pull/6560#discussion_r1320428761)) do not appear as direct MedGen::Mondo mappings in MedGen's `MedGenIDMappings.txt`.

I'm thinking that when Megan created these suggestions, they might have been the result of non-direct proxy mappings using a proxy like OMIM or Orphanet.

For now, we've asked Megan [to review](https://github.com/monarch-initiative/mondo-ingest/issues/273#issuecomment-1712658861) these cases.

## Actionable steps
a. We can just accept these mappings and wait until they are possibly reviewed by the MedGen team.
b. We could go ahead and remove them, and possibly follow up with MedGen team to consider having these formally added as direct mappings.

## Attachments
- [The 278 IDs not mapped directly to mondo in `MedGenIDMappings.txt`](https://github.com/monarch-initiative/mondo-ingest/files/12581005/medgen-mondo.matches.in.megans.conflicts.file.but.not.in.MedGenIDMappings.txt)

**Comment by kanems** [comment]
@joeflack4 Closing the loop on the issues from the gaps in the FTP file vs. my stand alone report. We have done some more analysis on our end and we do (for some still unknown reason) have some discrepancies in that FTP report. By my analysis, 90% or so of the mappings in the FTP file are correct and in agreement with our curated data. I think the gaps are small enough that the majority of the processing can proceed. 
The discrepancies in our FTP file affected multiple external IDs (not just Mondo) and will require a pretty deep dive by our developers to troubleshoot and fix the output to the FTP file.  I will work on reviewing the 278 cases that were not in agreement between the FTP file with my earlier report and give you a current, curated mapping with a goal of reviewing most in the next month or so.
 UMLS is has a November (2023AB) release, so we will likely have a batch of CNs IDs that can be updated in December once we've processed that update and run the appropriate QC checks. If Mondo wants to consider making this MedGen ingest a regular thing, we should have our CUI data updated from UMLS twice year in June and December (about a month after UMLS' data release).

**Comment by joeflack4** [comment]
Hey @kanems! Super appreciated for you / you guys are staying on this! I'll stay tuned on future updates.

Just highlighting a couple things for my future self / reference:
> we will likely have a batch of CNs IDs that can be updated in December
> we should have our CUI data updated from UMLS twice year in June and December (about a month after UMLS' data release).

Regarding making the MedGen ingest a regular thing, we do want to do that. There are a couple different ways we could do it. @matentzn will be making the decision on that and will be in communication with your team, though I don't know when that will be.

**Comment by matentzn** [comment]
@kanems @joeflack4 We are moving now to updating Mondo-medgen from the FTP ID report, see https://github.com/monarch-initiative/mondo/issues/7035. Can this issue be closed?

**Comment by joeflack4** [comment]
I think this is issue is wholly on the MedGen side now. There was a discrepancy between their mappings file and the ad hoc report that Megan made.

@kanems I'm gonna close this issue but just wanted to remind about this. You would have an idea as to whether or not this is actually a quality issue that you / others need to look into on your side.
