### ISSUE TITLE
The ORDO ingest is still broken

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#372]
@hrshdhgd 

I dont know what needs doing here, but this needs to go to the top of the pile.

Right now, _all_ of ORDO appears as unmapped:

https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/lexmatch/unmapped_ordo_lex_exact.tsv

This is most likely because still, the mondo.sssom.tsv uses the wrong ordo prefix. Can you hack the mondo pipeline in a away that we get the right prefix? You said it worked for you locally, but you may have used local versions of sssom-py that were never published. The problem happens here (most likely):

https://github.com/monarch-initiative/mondo/blob/master/src/ontology/mondo.Makefile#L575

and you need to find a way with the version of sssom-py in ODK that it uses the correct ORDO prefix.

**Comment by hrshdhgd** [comment]
This should be fixed by the new sssom 0.4.0 release, dependency on `curies` + updated `bioregistry` EPM.

**Comment by matentzn** [comment]
Is fixed now.

**Comment by twhetzel** [comment]
Did the "sssom 0.4.0 release" resolve the issue or something else and if so, was it a temp fix for now?

**Comment by matentzn** [comment]
Yes, partially. The problem was that sssom-py was not able to deal with conflicting prefixes correctly (it basically tried to keep both conflicting prefixes side by side rather than merging them)
