### ISSUE TITLE
Basic matching pipeline

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#38]
I would like to start working on a basic lexical matching pipeline for Mondo ingest. This is somewhat disconnected from all the rest.

The goal is to maintain a continuously updated set of lexical matches in this repo, release these mappings, and feed them to boomer by some kind of criteria. 

It is important the matches have a solid `confidence` value.

**Comment by matentzn** [comment]
I have provided a basic setup for you here: https://github.com/monarch-initiative/mondo-ingest/pull/39, please work on that branch.

You can run the pipeline by running:

```
cd src/ontology
sh run.sh make lexical_matches
```

**Comment by hrshdhgd** [comment]
So right now `oaklib`'s `lexmatch` gives me the following:

**command**: 
```
runoak -i src/ontology/tmp/merged-mondo-ingest-edit.owl lexmatch -L src/ontology/metadata/mondo.sssom.config.yml -o test.sssom.tsv
```
**test.sssom.tsv** :
```
# curie_map: {}
# license: CC-0
# mapping_set_id: default
```
Above is the `curie_map` and `metadata` that needs work but below is the mapping file (partial copy-paste)

| subject_id | subject_label | predicate_id | object_id | object_label | mapping_justification | mapping_tool | subject_match_field | object_match_field | match_string |
|---|---|---|---|---|---|---|---|---|---|
| NCIT:C100101 | Naratuximab Emtansine | skos:closeMatch | NCIT:C170199 | Naratuximab Emtansine | semapv:LexicalMatching | oaklib | rdfs:label | rdfs:label | Naratuximab Emtansine |
| NCIT:C1008 | Azaribine | skos:closeMatch | NCIT:C76914 | Azaribine | semapv:LexicalMatching | oaklib | rdfs:label | rdfs:label | Azaribine |
| NCIT:C101267 | Hormone Receptor Positive | skos:closeMatch | NCIT:C157055 | Hormone Receptor Positive | semapv:LexicalMatching | oaklib | rdfs:label | rdfs:label | Hormone Receptor Positive |
| NCIT:C102533 | Myopia | skos:closeMatch | http://www.omim.org/phenotypicSeries/PS160700 | Myopia | semapv:LexicalMatching | oaklib | rdfs:label | rdfs:label | Myopia |
| NCIT:C102533 | Myopia | skos:closeMatch | https://icd.who.int/browse10/2019/en#/H52.1 | Myopia | semapv:LexicalMatching | oaklib | rdfs:label | rdfs:label | Myopia |
| NCIT:C102877 | Olinvacimab | skos:closeMatch | NCIT:C170247 | Olinvacimab | semapv:LexicalMatching | oaklib | rdfs:label | rdfs:label | Olinvacimab |
| NCIT:C103296 | AIDS-Related Human Papillomavirus Infection | skos:closeMatch | NCIT:C27852 | AIDS-Related Human Papillomavirus Infection | semapv:LexicalMatching | oaklib | rdfs:label | rdfs:label | AIDS-Related Human Papillomavirus Infection |
| NCIT:C103301 | Progression of Multiple Myeloma or Plasma Cell Leukemia | skos:closeMatch | NCIT:C70643 | Progression of Multiple Myeloma or Plasma Cell Leukemia | semapv:LexicalMatching | oaklib | rdfs:label | rdfs:label | Progression of Multiple Myeloma or Plasma Cell Leukemia |
| NCIT:C103302 | Partial Response of Multiple Myeloma or Plasma Cell Leukemia | skos:closeMatch | NCIT:C70641 | Partial Response of Multiple Myeloma or Plasma Cell Leukemia | semapv:LexicalMatching | oaklib | rdfs:label | rdfs:label | Partial Response of Multiple Myeloma or Plasma Cell Leukemia |
| NCIT:C10345 | ICE Regimen | skos:closeMatch | NCIT:C63456 | ICE Regimen | semapv:LexicalMatching | oaklib | rdfs:label | rdfs:label | ICE Regimen |
| NCIT:C103863 | Istiratumab | skos:closeMatch | NCIT:C170084 | Istiratumab | semapv:LexicalMatching | oaklib | rdfs:label | rdfs:label | Istiratumab |
| NCIT:C103921 | Lissencephaly | skos:closeMatch | http://www.omim.org/phenotypicSeries/PS607432 | Lissencephaly | semapv:LexicalMatching | oaklib | rdfs:label | rdfs:label | Lissencephaly |
| NCIT:C104058 | Lumretuzumab | skos:closeMatch | NCIT:C170139 | Lumretuzumab | semapv:LexicalMatching | oaklib | rdfs:label | rdfs:label | Lumretuzumab |
| NCIT:C104197 | Cyclin E | skos:closeMatch | NCIT:C17490 | Cyclin E | semapv:LexicalMatching | oaklib | rdfs:label | rdfs:label | Cyclin E |


Is this what's expected?

**Comment by matentzn** [comment]
Awesome, you started already on this!! Super cool. A few things will have to be fixed in OAK: I created a collection ticket for this here:

https://github.com/INCATools/ontology-access-kit/issues/191

So it is probably good to set yourself up for a parallel OAK - Mondo matching development. Maybe use OAKs testing framework to work with the merged owl file. But I also do not know all the answers yet - this will require some observations.

I added some direct observations to your work here in a new discussion here:
https://github.com/monarch-initiative/mondo-ingest/discussions/40

This helps with commenting on individual ideas a bit more easily than trying to do everything in the PR.

**Comment by matentzn** [comment]
- [ ] If the prefix map is empty, you can make an OAK ticket to make sure it is populated correctly. The rest should be covered by the OAK tickets I already shared with you above, in particular, the need to produce a _valid_ sssom file.

**Comment by hrshdhgd** [comment]
> [x] If the prefix map is empty, you can make an OAK ticket to make sure it is populated correctly. The rest should be covered by the OAK tickets I already shared with you above, in particular, the need to produce a _valid_ sssom file.

The prefix_map issue is resolved in oak and it should reflect in the next release.
