### ISSUE TITLE
`develop` branch

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/mondo-ingest#404]
## Overview
@matentzn I had a meeting with @twhetzel and she came up with a great idea that we decided to move forward with. I always thought it was strange that we did not have a `develop` branch. It would probably solve more problems than we realized. Consider [this comment](https://github.com/monarch-initiative/mondo-ingest/pull/397#pullrequestreview-1843728252):
> Never ever again do we merge a branch unless a full run of the pipeline was successful. I can be responsible for the runs until we have a runner on GCP.

Trish brings up that this issue is likely solved by a `develop` branch. If for some reason we feel the need to merge a PR before the full pipeline has been successfully run, then nothing will break on the production build (`main`) if we simply merge into `develop`. We would merge to `develop` and then could run it on that branch from wherever (local, Nico's virtual machine, GCP, etc).

## Sub-tasks
- [x] 1. Create `develop`
- [x] 2. What to do w/ currently open PRs?
- [x] 3. Default branch
- [ ] 4. #405

### 1. Create `develop`
a. Create a new `develop` branch
b. Rename `main`->`develop`, and make a new `main` branch

I advise 'b'. See discussion in: _What to do w/ currently open PRs?_

### 2. What to do w/ currently open PRs?
a. Merge them in `main`, and possibly rebase `develop`.
b. Rename `main`->`develop`, and make a new `main` branch

I originally thinking 'a' since it felt safer, but I now think 'b' is much better. All our PRs will automatically be updated to merged into `develop`. See more in _Details_. 
<details><summary>Details</summary>
<p>

It looks like renaming the branch in GitHub is pretty safe, and GitHub has nice UX around this. See: [article](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch)

Just need to rename local branches after:
<img width="466" alt="Screenshot 2024-01-27 at 6 44 07 PM" src="https://github.com/monarch-initiative/mondo-ingest/assets/13045020/6f398456-99b7-4fb8-8a8a-81bb37832f8f">

Also I just did a backup of the `main` branch locally just in case.

</p>
</details> 

### 3. Default branch
If we rename `main` to `develop`, I think it will stay as the default branch. This means that even when we create a new `main`, `develop` will still be the default.

I haven't thought through or researched the pros/cons for this. Normally, in my experience, `main` is the default. However for TermHub we've had `develop` as our default for over a year with no problems.

**Comment by twhetzel** [comment]
Just in case this issue is read before Slack by Nico, please do not re-name the `main` branch.

**Comment by matentzn** [comment]
Interesting suggestion, I agree in principle but we should discuss this and the associated SOPs in a call where we are all present!

**Comment by twhetzel** [comment]
@matentzn agreed. There are some working processes we need to discuss and be aligned on, a few more than I realized initially based on the content of this repo.

**Comment by joeflack4** [comment]
Today we created the `develop` branch and changed the base of my 2 ICD11 PRs to `develop`. We left the other PRs as pointing to `main` and Nico said he plans to deal with that.

We left the default branch as `main`. The SOP (#405) is still in the works.
