### ISSUE TITLE
slurp/omim.tsv missing

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo-ingest#422]
following #421

The following slurp/omim.tsv file is missing.

Unmapped OMIM ids are reported in src/ontology/reports/omim_mapping_status.tsv (see image below), but these unmapped OMIM id are not in the slurp/omim.tsv. 

Note: the slurp/omim.tsv is the ROBOT template that we use to add new Mondo terms.

![Screenshot 2024-02-02 at 10 27 12](https://github.com/monarch-initiative/mondo-ingest/assets/12737987/fa7db376-8a23-4d5a-b1c9-6d04e60b828b)

**Comment by matentzn** [comment]
The migration file slurp/omim.md was somehow out of sync with the rest. I found the problem - a missing dependency on a migration related goal. To close this issue:

- [ ] Merge #427 
- [ ] Merge #429

**Comment by sabrinatoro** [comment]
this issue is resolved
