### ISSUE TITLE
OMIM import: parents missing

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo-ingest#438]
I am looking at this file src/ontology/slurp/omim.tsv (on Feb 12th, 2024). 

I expected some terms to have parents that exist in Mondo (based on being part of a phenotypic series), but they did not. For example: 
The following term exists in Mondo: [Lafora disease](http://purl.obolibrary.org/obo/MONDO_0009697) = OMIMPS:254780
The following terms were expected have 'Lafora disease' as parent (because they are in the OMIM phenotypic series): 
- myoclonic epilepsy of lafora 1  = OMIM:254780
- myoclonic epilepsy of lafora 2 = OMIM:620681

Notes
- none of the terms in the file had suggested parents, and 7/8 should have had parents as they are part of a phenotypic series in OMIM. 
- this issue is new (ie I could see parents in the previous omim.tsv). 
- After the terms reported in omim.tsv are added into Mondo, it might not be possible to see this. I will refer to this issue on the PR, and check before merging

**Comment by sabrinatoro** [comment]
Please is PR: https://github.com/monarch-initiative/mondo/pull/7268

**Comment by joeflack4** [comment]
@matentzn Can I have your eye before I consider diving into this?
I indeed do not see any parents at all in the `SC %` column in [the latest `slurp/omim.tsv`](https://github.com/monarch-initiative/mondo-ingest/blob/a02c26873328a942d15b9e987fd11d29c8b52022/src/ontology/slurp/omim.tsv).
However, in Sabrina's PR https://github.com/monarch-initiative/mondo/pull/7268/files, I do see parents:

<details><summary>Details</summary>
<p>

```obo
id: MONDO:0958199
name: myoclonic epilepsy of Lafora 1
xref: OMIM:254780 {source="MONDO:equivalentTo"}
is_a: MONDO:0009697 {source="OMIM:254780"} ! Lafora disease

[Term]
id: MONDO:0958201
name: myoclonic epilepsy of Lafora 2
xref: OMIM:620681 {source="MONDO:equivalentTo"}
is_a: MONDO:0009697 {source="OMIM:620681"} ! Lafora disease
```

</p>
</details> 

<details><summary>Additional fuzziness in my understanding</summary>
<p>

My obo understanding is a little fuzzy. I'm confused as to why there's an xref `MONDO:equivalentTo` to `OMIM:254780`, but it's also showing the same term as its parent. This seems like a contradiction to me. I must be misunderstanding something.

Additionally, I'm confused as to how `is_a` is getting set in these changes to `mondo-edit.obo` when the `slurp/omim.tsv` has nothing in the `SC %` column.

</p>
</details>

**Comment by sabrinatoro** [comment]
@joeflack4, please note that I manually added the parents to the spreadsheet in this [PR](https://github.com/monarch-initiative/mondo/pull/7268/files) 



> My obo understanding is a little fuzzy. I'm confused as to why there's an xref MONDO:equivalentTo to OMIM:254780, but it's also showing the same term as its parent. This seems like a contradiction to me. I must be misunderstanding something.
I am not 100% sure this is what you are asking, so ignore if it is confusing. 
1) OMIM:254780 = myoclonic epilepsy of Lafora 1 (child)
2) OMIM**PS**:254780 = Lafora disease = parent term (same number, but it is referring to the phenotypic series - OMIMPS)

**Comment by joeflack4** [comment]
@sabrinatoro Ohh, I see! I had forgotten to mention that [the spreadsheet](https://docs.google.com/spreadsheets/d/1Jph0vcyJ1Fcg97v4Xlc-8MDldDoUk38CCeA6gmFYwg0/edit#gid=0) didn't load for me; I had gotten an error. But now it loads and I see that!

**Comment by joeflack4** [comment]
Ahh, I see now. 
I was interpreting this wrong:
```obo
is_a: MONDO:0009697 {source="OMIM:620681"} ! Lafora disease
```
I thought this meant that `MONDO:0009697` == `OMIM:620681` but that is not what it's saying.

**Comment by matentzn** [comment]
@sabrinatoro step 1 here is always to check the new deployment of OMIM on monarch OLS:

https://ols.monarchinitiative.org/ontologies/omim/terms?iri=https%3A%2F%2Fomim.org%2Fentry%2F254780

1. From what you say, OMIMPS:254780 exists as an xref in Mondo
2. I futhermore assume that OMIMPS:254780 exists in mondo.sssom.tsv

Next step:
Does the OMIM ingest representation in OLS seem correct? (Parentage)

If so, it means that the "migrate" code is missing the parents somehow - which could have multiple reasons (including some remaining prefix shenaningans).

@joeflack4 dont worry about this issue, I will slowly iterate it forward, you focus on ICD11.

**Comment by sabrinatoro** [comment]
1) OMIMPS:254780 is present in the OMIM deployment on monarch OLS, with the expected children (ie parentage is as expected)
2) OMIMPS:254780 is in mondo-edit
3) OMIMPS:254780 is in mondo.sssom.tsv

@matentzn @joeflack4

**Comment by matentzn** [comment]
The next step is for @joeflack4 to figure out why this parentage is not included in the migrate scripts. This issue has higher priority than MedGen issues and should be checked quickly before everything else.

**Comment by joeflack4** [comment]
@sabrinatoro Sorry for the delay on this. I just completed #478 which addresses this issue.

**Comment by joeflack4** [comment]
#478 was linked to this and merged, but for some reason, this issue didn't auto-close, so I'm closing it now.
