### ISSUE TITLE
Represent Externally Managed Content in the Mondo Ingest

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#439]
Some providers such as NORD, GARD and MedGen directly provide content to Mondo which we pull in.

I would like to suggest, rather than adding a lot of spaghetti code to Mondo repo, to process _all_ external code here in the Mondo Ingest using this process:

1. We work with the content providers to provide us with a table with the information to pull in, say xrefs, labels, and / or subsets
2. We pull these tables and transform them into ROBOT templates here (OWL and TSV)
3. We reduce the code in the Mondo ingest rest (which is currently some hacky stuff which is in a draft PR here:  https://github.com/monarch-initiative/mondo/pull/6903) by a simple process (github action) that pulls the content from here and merges it into Mondo-edit (we dont need to answer the "how" here to move on - its a small change to what is already there).

The advantage is that we once and for all centralise all external content in the mondo ingest pipeline and have no side-loading shows for external content in Mondo repo. 

Note: Externally managed content are _not_ external resources in the sense of external terminologies like ORDO and OMIM. They are simply tables we download and merge into Mondo after we have agreed with the team and the external content provider that we should do so.

**Comment by twhetzel** [comment]
Agree, processing of the externally managed content should not occur in the `mondo` repo (and I didn't realize any processing was happening there).
