### ISSUE TITLE
`fix_complex_reification.ru` updates

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/mondo-ingest#469]
## Overview
Does this file only apply to ORDO?

I've since removed this line from the `icd11foundation` goal, but it's still on several other goals.

I ask because it at the end, it has:
```sparql
  FILTER (isIRI(?entity) && (regex(str(?entity), "http://www.orpha.net/ORDO/")))
  BIND(IF(STRSTARTS(str(?precision_value), "NTBT"), skos:narrowMatch, IF(STRSTARTS(str(?precision_value), "BTNT"), skos:broadMatch, oboInOwl:hasDbXref)) as ?property)
```

## Suggestions
- [x] 1. If it indeed only applies to ORDO, then I suggest we remove this line from all the goals except for ORDO, as done in PR with similar situation: #459.
- [x] 2. If that's the case, I suggest we also prepend `ordo_` to the filename (like I've suggest in similar situation https://github.com/monarch-initiative/mondo-ingest/pull/459#discussion_r1510414581).

---

- [x] Advise @matentzn / @twhetzel 
- [x] Implement any decisions @joeflack4

**Comment by matentzn** [comment]
Definitely (1) (remove this line from all the goals except for ORDO).

Thank you for spotting.

**Comment by joeflack4** [comment]
Thanks. And you didn't say no to (2), so I'm going to do that too unless I hear otherwise!

**Comment by joeflack4** [comment]
@souzadevinicius Just an FYI on some code cleanliness measures for `mondo-ingest`.

**Comment by joeflack4** [comment]
This has been completed.
