### ISSUE TITLE
Adding synonymizer config to matching pipeline

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#50]
I think the best way to handle the structural synonym matching is to:

- Create a synonymiser config the specifies all the rules for generating derived, preprocessed versions of labels (or other synonyms) as another synonym time, with an source annotation "MONDO:synonymizer" which points to the synonym generation config. This config should do stuff like:
   - Stripping out redundant parts of the terms (disease, disorder, of, to)
   - Replacing certain other ones ("aberrant" --> "abnormal")
   - General label normalisation - lowercasing, stemming (this could avoid much of the AE/BE issues). (extend synonymiser)
 - Add a synonymiser config to `src/ontology/config`
 - Add a step preceeding `mondo-ingest.db` which
    - computes a synonymiser table
    - outputs it as turtle (extend synonymiser)
    - merges it into mondo-ingest before transforming it to mondo-ingest.db
 
As soon as the general architecture stands (you can start with a rule that normalises "disorder" to "disease").

Note that I will want to use this later for other things, like enriching Mondo itself with synonyms.

**Comment by nicolevasilevsky** [comment]
- when we are doing matching, we want disorder to be replaced by disease
- type 1 -> Type I
- 1 -> type 1
- include 'the' in the label, eg abnormality of the face -> abnormality of face
- of
- plural
- 's, eg Usher's syndrome -> Usher syndrome

**Comment by matentzn** [comment]
Create a second output table like this:

| ID | Synonym | Source | Type |
| --- | --- | --- | --- |
| ID | A oio:hasExactSynonym | >A oio:source |  TYPE |
| MONDO:123 | The Synonym | MONARCH:Synonimizer | owl:Class |
| MONDO:222 | The Syn | MONARCH:Synonimizer | owl:Class |

**Comment by cmungall** [comment]
I would push for a slight variation:

have synonymizer output KGCL. That we decouple it from any implementation

You add then just apply these changes to the .db (or to the .obo if a curator wants them...)

**Comment by matentzn** [comment]
Yes you are right. That would make it possible to bypass robot in this pipeline. 

I still think synonymiser should be a method in oak though, see https://github.com/INCATools/ontology-access-kit/issues/281
