### ISSUE TITLE
Duplicate conflicting cases in `prefixes.csv`

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/mondo-ingest#502]
## Overview
I found these duplicate cases in `prefixes.csv`, which is used by SemSql.

|prefix|uri_prefix|
|----|------------------------------------|
|UMLS|http://purl.obolibrary.org/obo/UMLS_|
|UMLS|http://linkedlifedata.com/resource/umls/id/|
|SCTID|http://snomed.info/id/              |
|SCTID|http://identifiers.org/snomedct/    |
|HGNC|http://identifiers.org/hgnc/        |
|HGNC|https://identifiers.org/hgnc/       |

I don't know if this is causing any problems for us right now.

Note that it might be worth checking other such maps, such as `config/context.json`. And also the `curie_map` in `metadata/mondo.sssom.config.yml`. Even though we've already made a `extended_prefix_map` in that config which does handle prefix synonyms, `curie_map` still exists (I don't remember why / how it's used). 

I'm not sure which of these is more authoritative than the other, but I could check our `extended_prefix_map` and that might answer it for me.

## Additional info
#503 is sort of related. The difference between this issue and that PR is that in that PR, both the prefix and the URI prefix in all cases were the same; so they were pure duplicates. In this issue, the prefix is the same, but the URI prefix is different for each case.

**Comment by joeflack4** [comment]
FYI @twhetzel

**Comment by matentzn** [comment]
I think prefixes.csv, the format needed to feed into the semsql process is a unidirectional prefixmap whose sole purpose it is to rewrite IRIs to CURIEs. So duplicate entries as memory serves should be fine, because we would want to map different sources with different IRI schemes to the same prefix / curie scheme

**Comment by joeflack4** [comment]
> sole purpose it is to rewrite IRIs to CURIEs

Ahhh, but not the other way around. If Harshad was here at the moment I'd ask him to confirm. I will try to remember this...
