### ISSUE TITLE
Create ORDO subset ROBOT template

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#509]
This is a bit ad hoc, but we need it asap to fix the RD subset before the next release (in agreement with what we discussed with Orphanet). 

https://www.ebi.ac.uk/ols4/ontologies/ordo

I need using the raw  ORDO source, not mondo-ingest-ordo component (which has a different classification) and the currently up to date mondo.sssom.tsv.

A file with the following columns:

- mondo_id (from mondo.sssom.tsv - we dont care about cases where there is no Mondo id)
- ordo_id
- subset

where subset has one of the following values

- `http://purl.obolibrary.org/obo/mondo#ordo_group_of_disorders` (if its a Group of disorders, see screenshot)
- `http://purl.obolibrary.org/obo/mondo#ordo_clinical_subtype` (if its a Subtype)
- `http://purl.obolibrary.org/obo/mondo#ordo_disease` (if it is a disease/disorder).

Ideally robot template but anything goes. Thank you!

<img width="471" alt="image" src="https://github.com/monarch-initiative/mondo-ingest/assets/7070631/c2f95c6d-45cd-4422-bc8c-1f705eec2044">

For now we can just generate this list in an adhoc manner, and I can make a more detailed ticket to add it to the release products.

Thank you!

**Comment by twhetzel** [comment]
@matentzn - overall sounds like it should be straightforward, but I don't have a lot of context on what was done or the issue of what is wrong.

(1) is this the location you want for the ORDO file (this is the value from OLS for the Ontology IRI):  https://www.orphadata.com/data/ontologies/ordo/last_version/ORDO_en_4.4.owl

(2) which RD subset needs to be updated, the `orphanet_rare` or other subsets tagged with some "rare" term, e.g `rare`, `rare_grouping`, etc

(3) Where is the `mondo.sssom.tsv` file?

(2) will this ROBOT template need to be reviewed by curators?

**Comment by matentzn** [comment]
(1) yes, exactly! 
(2) - no need, just the three subsets I mention in the ticket. The subsets you mention are updated already on the mondo side of things
(3) there is a corresponding goal in the mondo ingest makefile to get it which is the only way to get an up to date version 
(4) I will deal with that part - let's talk about this pipeline after the release 
(5) no, no review necessary

**Comment by twhetzel** [comment]
Is there some code or a Makefile goal that the new ORDO URL needs to be swapped into and re-run? Joe and I are looking through things now, but not seeing much yet to know what to do.

**Comment by joeflack4** [comment]
Here's what we think is being asked and what we're going to do:

1. Query ORDO to get TSV w/ 2 cols: class name, subset
  - subset will be 1 of "disorder", "group of disorders", "subtype of disorder"
2. Remap subset:
  - disorder --> http://purl.obolibrary.org/obo/mondo#ordo_disease
  - group of disorders --> http://purl.obolibrary.org/obo/mondo#ordo_group_of_disorders
  - subtype of disorder --> http://purl.obolibrary.org/obo/mondo#ordo_clinical_subtype
3. Write the robot template

**Comment by joeflack4** [comment]
For step (1), here's the resulting SPARQL query

<details><summary>Details</summary>
<p>

```sparql
# http://www.orpha.net/ORDO/Orphanet_557493  # disorder
# http://www.orpha.net/ORDO/Orphanet_557492  # group of disorders
# http://www.orpha.net/ORDO/Orphanet_557494  # subtype of a disorder
prefix oio: <http://www.geneontology.org/formats/oboInOwl#>
prefix phenome: <http://www.orpha.net/ORDO/Orphanet_C001>
prefix ms: <http://purl.obolibrary.org/obo/mondo#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix BFO: <http://purl.obolibrary.org/obo/BFO_>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?cls ?lbl ?grp ?grp_lbl
WHERE {
    VALUES ?grp {
        <http://www.orpha.net/ORDO/Orphanet_557493>
        <http://www.orpha.net/ORDO/Orphanet_557492>
        <http://www.orpha.net/ORDO/Orphanet_557494>
    }
    ?cls rdfs:subClassOf+ ?grp .
    ?cls rdfs:label ?lbl .
    ?grp rdfs:label ?grp_lbl .
}
```

</p>
</details>

**Comment by matentzn** [comment]
Yes! Awesome plan! Thaaank you!

**Comment by joeflack4** [comment]
Addressed by:
- #510
