### ISSUE TITLE
Filter matches to only relevant prefixes

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#51]
The lexical matching pipeline should only contain matches between:

https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/metadata/mondo.sssom.config.yml#L26

- [x] Filter all matches according to the prefixes above
- [x] Ensure that all prefixes in that list occur at least once in the resulting mapping set

**Comment by hrshdhgd** [comment]
Fixed by #52
