### ISSUE TITLE
Add the orphanet subset to the Slurp file

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo-ingest#527]
when reviewing the slurp/ordo.tsv, it would be helpful to know whether the orphanet term is in the "grouping disease", "disorder", or "subtype of disease" subset in orphanet. 
Please add a column in the slurp/ordo.tsv for the orphanet subset. Thank you!

**Comment by joeflack4** [comment]
That sounds helpful! I will be happy to help out.

Thoughts for myself about implementation:
- Have a goal that runs at end of subclass synchronization pipeline for additional modifications
- That goal can run a separate goal that makes the modification to add these to orod
  - easiest way is a Python script, but maybe there's another way

**Comment by joeflack4** [comment]
I'm not the user of these outputs, so I can't say how useful it is to have this subset info in `reports
/ordo-subsets.robot.template.tsv` vs in `slurp/ordo.tsv` as @sabrinatoro is asking. But they are different files each with different information, and have different numbers of rows.

`reports
/ordo-subsets.robot.template.tsv` ([9348 rows](https://github.com/monarch-initiative/mondo-ingest/blob/2523cd89915d070a1a4b8b4c9a91dacb244561d9/src/ontology/reports/ordo-subsets.robot.template.tsv)):
|mondo_id|subset|ordo_id|mondo_label|ordo_label|
|-|-|-|-|-|
|ID|A oboInOwl:inSubset|>A oboInOwl:source| | |

`slurp/ordo.tsv` ([13 rows](https://github.com/monarch-initiative/mondo-ingest/blob/2523cd89915d070a1a4b8b4c9a91dacb244561d9/src/ontology/slurp/ordo.tsv)):
|mondo_id|mondo_label|xref|xref_source|original_label|definition|parents|
|-|-|-|-|-|-|-|
|ID|LABEL|A oboInOwl:hasDbXref|>A oboInOwl:source SPLIT="|| |A IAO:0000115|SC %|

**Comment by matentzn** [comment]
@joeflack4 you are right, thanks for correcting me. #510 is sync, the request is for migrate and serves multiple purposes:

1. ORDO sourced diseases immediately have the correct subset (no delay waiting for sync)
2. The editor knows "aha, this is a group of disorders, maybe I should obsolete it rather than add it".


So forget what I said, and thanks for the correction!

**Comment by joeflack4** [comment]
Addressed by:
- #531
