### ISSUE TITLE
Goal &/or SOP for updating `mondo.sssom.tsv`

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/mondo-ingest#529]
## Overview
Unfortunately, the goal / nature of updating `mondo.sssom.tsv` is different than other artefacts. It does not suffice to simply delete the file and run the goal.

## Sub-tasks
- [ ] a. Goal
- [ ] b. SOP
  - [ ] b.i. Decide on the procedure
  - [ ] b.ii. Write the SOP

#### a. `make tmp/mondo.sssom.tsv -B`
This is [what I proposed](https://github.com/monarch-initiative/mondo-ingest/pull/510#discussion_r1597500072). I don't know if there is some reason why it wouldn't work or otherwise if it has any downsides.

#### b. `rm tmp/mondo_repo_built tmp/mondo.sssom.tsv; make tmp/mondo.sssom.tsv`
Nico [proposed this](https://github.com/monarch-initiative/mondo-ingest/pull/510#discussion_r1597374539).

## Additional info
Context: [discussion where the idea for this SOP came up](https://github.com/monarch-initiative/mondo-ingest/pull/510#discussion_r1597374539)

If need inspiration for writing SOP, look at this as an example: https://mondo.readthedocs.io/en/stable/editors-guide/mondo-docs-website-editing/

Related:
- #538

**Comment by joeflack4** [comment]
@matentzn It seems to me that 'a' should work and is simpler. Do you think it is the best option or is 'b' better?

**Comment by matentzn** [comment]
I think for this very isolated request "refreshing mondo.sssom.tsv" they are identical, and your solution is ok. The problem comes when you want to run larger pipelines that depend on mondo.sssom.tsv - you cant just use `-B` in those unless you want to re-run absolutely everything! I am just telling you how I would do it, you do whatever you prefer. Both have the same effect in the end - mondo.sssom.tsv will be refreshed. but `-B` invalidates _all_ the `make` cache, which means that everything else is rerun as well!

**Comment by twhetzel** [comment]
Given the past issues we've run into with `-B` and it's effects on running pipelines, I would prefer option (b) since it sounds like it will work for both the issue of "refreshing mondo.sssom.tsv" and be able to be used within the context of larger pipelines.

**Comment by joeflack4** [comment]
Thanks for your thoughts, guys.

Oh, I just thought of this, if you guys don't mind me adding, can I do this instead?:

Create a goal:
```make
.PHONY: refresh-mondo-sssom
refresh-mondo-sssom:
    rm tmp/mondo_repo_built tmp/mondo.sssom.tsv
    $(MAKE) tmp/mondo.sssom.tsv
```

**Comment by matentzn** [comment]
Yes no problem.

**Comment by joeflack4** [comment]
This has been replaced by:
- #538
