### ISSUE TITLE
Re-use cthoyt:curies for all curie to uri and uri to curie operations

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#53]
This issue can be closed if either @joeflack4 or @hrshdhgd make a single PR using the lib.  :) You can sort out who does this first, bit no priority.

**Comment by matentzn** [comment]
https://github.com/cthoyt/curies

**Comment by cmungall** [comment]
how this has been folded into OAK, is this task done?

**Comment by hrshdhgd** [comment]
I haven't worked on this. Joe?

**Comment by joeflack4** [comment]
I have a little bit. I don't have time to go through the entire `mondo-ingest` at the moment and make all the replacements, but I've done some, and ongoing will be using `oaklib` and `curies`. As I think I've done the major part of addressing this, I've changed itfrom high to low priority on [the project board](https://github.com/orgs/monarch-initiative/projects/23/views/1?filterQuery=curie).

**Comment by matentzn** [comment]
@hrshdhgd you may not need it directly if you only work with OAK abstractions. I am using it in custom code here and there. Will close this now, this was just a reminder for everyone to not again wrote curie to URI conversion code.
