### ISSUE TITLE
Add merged exclusion table (in OBO/TTL/TSV format?)

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#54]
We should

- [x] 1. Add a merged exclusion file with all exclusions in it in various formats
  - [x] 1.1. TSV
  - [x] 1.2. TXT
  - [x] 1.4. TTL?
- [ ] 2. Link this table in the official mondo documentation as the place to look for "why an id is missing".

cc @nicolevasilevsky

**Comment by joeflack4** [comment]
@matentzn I created some extra checkboxes. TSV and TXT should be easier for me. I will try to do this merging using ShellScript instead of Python.

I am not clear though on the TTL or OBO output. I don't know what these will be used for, and I'm not 100% clear on what to include in those files, but I can guess that I would need to include, for each class, (i) CURIE/ID (of course), (ii) label. I'm also not sure how to create OBO files.

**Comment by joeflack4** [comment]
### Docs link related questions
**1. Where?**
I searched the `mondo-ingest` `docs/` folder for the word "missing", and I only got 1 unrelated results.

**2. How?**
I'm wondering if the link should be (a) a relative path to the file (I am not sure if that will actually do anything), or (b) a link directly to the file's location on GitHub (`main` branch of `mondo-ingest` after merge), or (c) something else?

**Comment by matentzn** [comment]
- If you make sure the TSV is a ROBOT template (as the individual ones are) then we can just use robot to create a TTL OBO etc. The merged TSV should be a all the individual ROBOT template TSVs merged together. That is all we need for now.
- For the docs, just add a comment in this issue, linking Nicole, and tell her to add a page to the official Mondo docs. She manages that. This is user facing. Maybe a FAQ in mondo docs. In any case, for this purpose a link to the github file location is fine, no need to sweat it.

**Comment by joeflack4** [comment]
Re-opening. The PR closed this, but there are still some outstanding tasks.

**Comment by joeflack4** [comment]
@matentzn Ah, I see. From the `robot template --help`:
> `robot template --input <file> --template <file> --output <file>`

I just started work on this. I had some success, but some issues. I just opened [a PR](https://github.com/monarch-initiative/mondo-ingest/pull/63). I'll share more information there.

**Comment by joeflack4** [comment]
@nicolevasilevsky Nico asked me to ping you regarding the docs part of this issue: https://github.com/monarch-initiative/mondo-ingest/issues/54#issuecomment-1209297764

**Comment by nicolevasilevsky** [comment]
Thanks @joeflack4. I'll update the documentation

**Comment by joeflack4** [comment]
We decided against OBO for now.

**Comment by nicolevasilevsky** [comment]
@joeflack4 could you please point me to the link to the merged exclusion table? Thank you!

**Comment by joeflack4** [comment]
@nicolevasilevsky Here's the link to the problematic exclusions: [reports/excluded_terms_in_mondo_xrefs.tsv](https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/reports/excluded_terms_in_mondo_xrefs.tsv)

However, if you want the list of all expanded exclusions, not just the problematic ones, you'd one of the following: 
a. `reports/term_exclusions.txt`
b. `reports/exclusion_reasons.robot.template.tsv`

Right now, these files are in `.gitignore`, though. I think I need to re-run them, and I can attach them here.
@matentzn Do you want those above files ('a' and 'b') committed as well? If so, do you want just the merged files committed, or all of the 'by ontology' ones as well (`*_term_exclusions.txt`, `*_exclusion_reasons.robot.template.tsv`)?

@matentzn Also wondering if I should rename `term_exclusions.txt` to something like `exclusions.txt`, `exclusions_expanded.txt`, or `exlusions_all.txt`. That would make it easier to find alphabetically.

**Comment by matentzn** [comment]
If they are smaller than 20MB yes, if they are larger, we will list all exclusion tables individually in the docs.

**Comment by joeflack4** [comment]
@matentzn OK, looks like they are. And only one of the `.ttl` files is not. I'll explicitly create exceptions for the the `*_exclusion_reasons.robot.template.tsv` and `*_term_exclusions.txt` only at this time.

I assume you're mentioning 20MB because of GitHub's file size limit. Another strategy would be: adding more exceptions to the `.gitignore`  and start committing more files, and simply handle cases that are greater than 20MB as they arise.

**Comment by joeflack4** [comment]
@nicolevasilevsky These files are committed now:
- https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/reports/exclusion_reasons.robot.template.tsv
- https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/reports/term_exclusions.txt

The corresponding files for each ontology are also now committed in the `reports/` dir. I've added explanations about these files to the `reports/REAMDE.md`.

**Comment by matentzn** [comment]
This is great, thank you @joeflack4 

The ICD 10 exclusion reasons are still the old ones. Is @sabrinatoro instructed how she can update these?

**Comment by matentzn** [comment]
In any case, @nicolevasilevsky 

Now you can make a PR in the user documentation for Mondo (FAQ):

```
# What if I cannot find a specific code / term mapped to a Mondo ID?

There are two main reasons why a code or a term from another ontology, vocabulary or terminology is not mapped to Mondo yet. 

1. The term is relatively new and the Mondo synchronisation pipeline has not captured it. If the term is newer than 3 months, the term will usually only appear in the next Mondo release.
2. The term was explicitly excluded. If you want to know if and what a specific term was excluded, see [list of excluded terms](https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/reports/exclusion_reasons.robot.template.tsv)

In rare cases, a term is excluded because of a mistake in the curation. This can happen, for example, when a relevant disease term exist in a branch of a source ontology, like NCIT, that is not tracked by Mondo. In this case, we encourage you to make an issue on the [Mondo issue tracker](https://github.com/monarch-initiative/mondo/issues) to let us know.
```

@nicolevasilevsky please close this issue here as soon as the pull request is ready and link the pull request to this issue.

**Comment by joeflack4** [comment]
[_Nico wrote:_](https://github.com/monarch-initiative/mondo-ingest/issues/54#issuecomment-1221237497)
> The ICD 10 exclusion reasons are still the old ones. Is @sabrinatoro instructed how she can update these?
I think Sabrina can update whenever. There is just the matter of further non-automatic updates that need to be made, I think, once the ICD10CM exclusions GoogleSheet is updated. If I remember correctly, the steps are (i) update the exclusions GoogleSheet for an ontology, (ii) download that as TSV and put in `reports/`, (iii) run the `make` command, (iv) add updated files and commit. 

Unfortunately still a lot of manual steps ;(. I know it's going to be awhile until everything is automated.

I don't think this [Mondo repo LinkML config exclusion reasons PR](https://github.com/monarch-initiative/mondo/pull/5288#issue-1343706446) is a hold-up, but I think @nicolevasilevsky still needs to approve and I'm assuming @matentzn approves of this being merged.

**Comment by nicolevasilevsky** [comment]
I added the FAQ and closed the issue but please reopen @joeflack4 if some steps are still needed

**Comment by joeflack4** [comment]
@nicolevasilevsky I think this one's done. As long as added the FAQ also includes the link Nico mentioned in (2) of the OP, we're all wrapped up here!
