### ISSUE TITLE
Update ICD11 relevant SPARQL query to exclude classes in the Extension Code branch

### ISSUE THREAD

**Issue by twhetzel** [monarch-initiative/mondo-ingest#547]
Update `src/sparql/icd11foundation-relevant-signature.sparql` to exclude any class that is a child of the Extension Code branch.

**Comment by twhetzel** [comment]
Joe - here is the SPARQL query. I'll leave the code update/branch management, etc. for you.
```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?term
WHERE {
  { 
    { 
      ?s1 ?p1 ?term . 
      ?term rdfs:subClassOf* <http://id.who.int/icd/entity/455013390> .
    }
    UNION
    { 
      ?term ?p2 ?o2 . 
      ?term rdfs:subClassOf* <http://id.who.int/icd/entity/455013390> .
    }
  }
  FILTER(isIRI(?term))
  FILTER NOT EXISTS {
    ?term rdfs:subClassOf* <http://id.who.int/icd/entity/979408586> .
  }
}
```

**Comment by twhetzel** [comment]
Here is the hierarchy view of ICD11 Foundation from the WHO site to show why subclasses of `Extension Codes` are being excluded. The branch has terms that are not relevant, but would otherwise be included since `Extension Codes` also have `ICD Category` as a parent.

![icd11foundation - extension codes](https://github.com/monarch-initiative/mondo-ingest/assets/2167174/af20a2fe-5dac-460e-8b63-463548d3f82c)

**Comment by joeflack4** [comment]
Thanks for creating the query for me! The screenshot is also helpful. Going to add this and begin a new build to `main`.
