### ISSUE TITLE
AttributeError: 'Series' object has no attribute 'iterrows'

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/mondo-ingest#583]
## Overview
If, while the lexmatch pipeline is running, it is processing a dataframe where there are no values in the `confidence` column (all are `nan`), this error occurs in `sssom-py`.

## Related
- #581 
- #578 
- https://github.com/mapping-commons/sssom-py/issues/546
- #585

**Comment by matentzn** [comment]
See also: https://github.com/mapping-commons/sssom-py/issues/546

**Comment by joeflack4** [comment]
Fixed by #581
