### ISSUE TITLE
Make sure all files generated by exclusion pipeline have standardised line sorting

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#66]
Right now, many files we generate during the exclusion pipeline runs create spurious diffs with slightly change line numbers. We should make sure that git diff only ever shows the immediately relevant changes.

**Comment by joeflack4** [comment]
Example of spurious diff: https://github.com/monarch-initiative/mondo-ingest/pull/63/files/4f03c3682b24a1541f9fbd9442e7dfbb27a4b43b#diff-1100a129b01ba0b1293a5e130655fbbf3b3f241292ac87090f235f584954d0ce

I think this can be solved by adding sorting as a step when generating our files (e.g. mirror_signature, component_signature, etc).

**Comment by matentzn** [comment]
@joeflack4 

This is now getting more urgent as we have plenty of new tables being checked in every week now. Esp. Exclusion reasons etc should be sorted somehow!

**Comment by joeflack4** [comment]
@matentzn I'll add sorting to outputs now for (i) slurp, (ii) exclusions. I'll include all columns in the sorting for guaranteed consistency.

For any other artefacts earlier in the pipeline (e.g. signature files, if that's necessary), I'll wait for any word / instruction.

I'll add this sorting update to existing PR #100

**Comment by matentzn** [comment]
Excellent, thank you!
