### ISSUE TITLE
Fix problem with ORDO ingest

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#67]
The ordo "relevant signature" pipeline is broken. It operates on RAW ORDO, while it should operate on the fixed version where part of are replaced by isa.

**Comment by matentzn** [comment]
@nicolevasilevsky I need your help with this. Can you:

1. Download this version of ORDO: https://www.dropbox.com/s/j1ed8sxaoa9xkfi/ordo-comp.owl?dl=0
2. Tell me what the root classes are we need to sync up with:

<img width="255" alt="image" src="https://user-images.githubusercontent.com/7070631/184507584-60739214-9c47-4235-b3bd-4c053e8dcba1.png">

I think there are classes in Mondo synced up from _any_ of these three branches. Just syncing the `disease` branch (under disorder) yields a tiny fraction of ORDO (4000 diseases). This could be correct, but I wanted to confirm, because there are about 3500 xrefs in Mondo pointing to ORDO IDs outside the disease branch see #31 .

**Comment by matentzn** [comment]
all three combined are about 9500 ids

**Comment by nicolevasilevsky** [comment]
Yeah, I think we want to sync with those three branches. I don't really understand the distinctions between the three classes, but yes, it seems like the equivalent Mondo terms are present in all three of those branches.
