### ISSUE TITLE
Bug: Synonym Sync: `-confirmed` has non-exact entries

### ISSUE THREAD

**Issue by twhetzel** [monarch-initiative/mondo-ingest#687]
There are two Mondo terms where the Synonym Sync pipeline adds source evidence for a confirmed synonym where the Synonym Sync pipeline should not. These Mondo terms from the qc check are: 
```
http://purl.obolibrary.org/obo/MONDO_0012817,Ewing sarcoma,NCIT:C7542,PNET of Thoracopulmonary region,MONDO:relatedTo
http://purl.obolibrary.org/obo/MONDO_0002514,hepatobiliary neoplasm,DOID:3117,hepatobiliary tumors,MONDO:mondoIsBroaderThanSource
```

These should be sorted out with high priority to resolve this issue, but it is not blocking the existing work on the Synonym Sync pipeline from being merged and getting into `main`. So #93 and #671 should be merged before working on this at this time.

**Comment by joeflack4** [comment]
resolved by:
- #695
