### ISSUE TITLE
Complete all "Week 4" steps of Mondo Ingest Development and Build Cycle for Synonym Sync added code

### ISSUE THREAD

**Issue by twhetzel** [monarch-initiative/mondo-ingest#702]
After PR #701 is reviewed (note this is a test build and does not get merged), then follow all steps in the Mondo Ingest and Development and Build Cycle document for "[Week 4](https://docs.google.com/document/d/1ylU_U595-Ufm-RMBoziAoPSRS8WpJ9pcPHXEKrO7nuk/edit?tab=t.0#heading=h.6utguqj7ejr)".

**Comment by twhetzel** [comment]
Nico changed his mind and said he can work on the other issues in the EMC pipeline and OMIM gene pipeline without the "Week 4" steps being done right now.

**Comment by matentzn** [comment]
I followed all steps exactly, should be done now!
