### ISSUE TITLE
Why is D35.2 not in the sssom table?

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#77]

**Comment by hrshdhgd** [comment]
It seems like this is in the `lexmatch` table (under `subject_id`) but not in the Mondo mappings table.

**Comment by matentzn** [comment]
Changed the name. `D35.2` should be mapped in the sssom table to MONDO:0021439. Its not?

**Comment by matentzn** [comment]
Ok so then the issue 

>  It seems like this is in the lexmatch table (under subject_id) but not in the Mondo mappings table.

Does not exist anymore?

**Comment by hrshdhgd** [comment]
That is correct.

**Comment by matentzn** [comment]
Thanks for confirming :)
