### ISSUE TITLE
ICD 10 WHO Ingest

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#8]
- [ ] Create an ingest according to the principles outlined in #2

**Comment by joeflack4** [comment]
Assigned myself as a participant in this; not necessarily as the only one who'll be responsible for completing it.

**Comment by matentzn** [comment]
See https://icd.who.int/icdapi

**Comment by matentzn** [comment]
1. Access the API to obtain the latest release
2. With the latest release, obtain the list of chapters

![image](https://user-images.githubusercontent.com/7070631/159308043-d3bea7c4-79b4-48c5-81bd-af8451541a61.png)


3. Crawl down all chapters to all codes recursively
4. Obtain three things:
     - code
     - label
     - parent

Safe all that as as an rdf file.

**Comment by matentzn** [comment]
- [ ] Create new repo in the monarch-initiative org (you can simply create it in your own space @joeflack4 and we migrate it when its done)
- [ ] Build a simple script that crawls the API and outputs ttl
- [ ] The rest (repo layout etc) I will assign someone else later (@deepakunni3)

**Comment by joeflack4** [comment]
Basic ingest has been created: https://github.com/monarch-initiative/icd10who/releases/tag/latest

Not yet compliant, though, with #2

**Comment by matentzn** [comment]
I will close this now, your work is done! Thank you @joeflack4 - I will take care of ingest structure etc.
