### ISSUE TITLE
Add all OMIM genes to exclusion table

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#82]
Just use a simple sparql query (one-off) to get all the subclasses of SO:Gene. Add them to the OMIM exclusions table with the corrected exclusion reason (I think MONDO:Gene).

**Comment by joeflack4** [comment]
Done! https://github.com/monarch-initiative/mondo-ingest/commit/e8abb0f370dc447c0aa4d4af24affc9b9118434b

I ran using robot:
```sparql
prefix SO: <http://purl.obolibrary.org/obo/SO_>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select ?child_id ?child_label where {
    ?child_id rdfs:subClassOf* SO:0000704 .
    ?child_id rdfs:label ?child_label
}
```

Then I did ETL to convert to CURIEs and added to the table. Going to utilize this in slurp now.
