### ISSUE TITLE
Exclusions: How to handle null `exclude_children`?

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/mondo-ingest#83]
## Overview
I noticed a bug in `scripts/exclusion_term_expansion.py`:
```python
    df_kids1 = exclusions_df[exclusions_df['exclude_children'] == False]
    df_kids0 = exclusions_df[exclusions_df['exclude_children'] == True]  # <-----
```

Changed that line to:
```python
    df_kids0 = exclusions_df[exclusions_df['exclude_children'] != True]
```

The bug was causing empty exclusion tables to be generated when running the script.

I hope I interpreted this correctly. If `exclude_children` is null/empty, should I indeed interpret it this way? Or the opposite way? Or raise an error?

Current files that are missing values for `exclude_children`:
- `config/omim_exclusions.tsv`
- `config/doid_exclusions.tsv`

**Comment by matentzn** [comment]
Good question. Lets err on the safe side. 

If and only if `exclude_children` is TRUE exclude children. Otherwise dont.

**Comment by joeflack4** [comment]
Ok, sounds good. Then it seems implicit that if `exclude_children` is blank/null, interpret it as FALSE, which is what I've done.

**Comment by matentzn** [comment]
Can we close this then?

**Comment by joeflack4** [comment]
Sounds like you approve of teh defaulting to `FALSE` for now, so let's go ahead and close. We can always revisit this if we want to change that, print warnings, etc.
