### ISSUE TITLE
OMIM Ingest: Invalid refs to `OMIM:1` -> `OMIM:14`

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/mondo-ingest#98]
## Overview
These terms are showing up in our OMIM ingest, but they don't resolve. E.g.: https://omim.org/entry/1

See if we can figure out what's going on here.

## Initial investigation
In our generated `omim.ttl`, these classes themselves are not defined. However, other classes have relationships with them. Example:

```ttl
OMIM:606082 a owl:Class ;
    rdfs:label "goiter, multinodular 3" ;
    RO:0003303 OMIM:3 ;  # <------------------
    rdfs:subClassOf OMIMPS:138800 ;
    skos:exactMatch UMLS:C1853686 ;
    biolink:category biolink:Disease .
```

I took an initial look but still not seeing the cause. Looks like I'll need to open the debugger and investigate more deeply.

@matentzn Gonna prioritize this ahead of the sync work, I think.

## Related
1. https://github.com/monarch-initiative/omim/issues/74

**Comment by joeflack4** [comment]
I shoulda also probably created this under the OMIM repo, but w/e.

**Comment by joeflack4** [comment]
## Initial results of analysis
I created this output: [confusingMimNums.csv](https://github.com/monarch-initiative/mondo-ingest/files/9740441/confusingMimNums.csv)

Some sample rows:
```csv
phenotype,gene_symbols,cyto_location,mim_number,mim_number.page,phenotype.label_mim_number,phenotype.mapping_key,phenotype.mapping_desc
"?Retinitis pigmentosa, X-linked recessive, 6 (2)",RP6,"Xp21.3-p21.2
",312612,https://omim.org/entry/312612,6,2,The disorder has been placed on the map by linkage or other statistical method; no mutation has been found.
"Alopecia, androgenetic, 1 (2)","AGA1, MPB","3q26
",109200,https://omim.org/entry/109200,1,2,The disorder has been placed on the map by linkage or other statistical method; no mutation has been found.
"Alopecia, androgenetic, 2 (2)",AGA2,"Xq11-q12
",300710,https://omim.org/entry/300710,2,2,The disorder has been placed on the map by linkage or other statistical method; no mutation has been found.
```

**Comment by matentzn** [comment]
As always, excellent investigation @joeflack4.

I trust your judgement to get to the bottom of this! I think reaching out to OMIM is a good idea, ccing me and @nicolevasilevsky, and asking them if our interpretation of the column is correct, and what this number exactly refers to. Try to formulate it a bit concisely though.

1. This is the column
2. We interpret it like that
3. but there are some (all?) values that do not seem to be valid MIM numbers. What are these?

something like that!
