### ISSUE TITLE
Investigate: ORDO terms showing up in slurp that shouldn't be there

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/mondo-ingest#99]
## Overview
There are some terms from ORDO that are showing up in slurp output that shouldn't be there. @nicolevasilevsky @matentzn If you remember why they shouldn't be there, if you could add a comment, that'd be helpful. But I'm assuming they fail to meet one of the conditions in my 'things to check' below.

## Things to check
If any of these is 'yes', then it means they shouldn't be in the slurp output.
- [x] 1. Has the term already been mapped? (i.e. is it in `mondo.sssom.tsv`)
    Answer: Yes  <------- problem
- [x] 2. Have any of the parents not been mapped?
    Answer: No

@matentzn If you think of anything else I can check, let me know.

## Examples
- Orphanet:454831
- Orphanet:101334

**Comment by matentzn** [comment]
They are already in mondo.sssom.tsv!

**Comment by joeflack4** [comment]
See #100 for fix.
